# Environment Setup

In [ ]:
!uv pip install bitsandbytes xformers triton unsloth vllm==0.10.2
!uv pip install transformers==4.55.4
!uv pip install --no-deps trl==0.22.2

Using Python 3.12.12 environment at: /usr
Resolved 166 packages in 1.11s
Prepared 50 packages in 10.09s
Uninstalled 9 packages in 520ms
Installed 50 packages in 81ms
 + astor==0.8.1
 + bitsandbytes==0.48.1
 + blake3==1.0.8
 + cbor2==5.7.0
 - click==8.3.0
 + click==8.2.1
 + compressed-tensors==0.11.0
 + cut-cross-entropy==25.1.1
 - datasets==4.0.0
 + datasets==4.2.0
 + depyf==0.19.0
 + diskcache==5.6.3
 + dnspython==2.8.0
 + email-validator==2.3.0
 + fastapi-cli==0.0.14
 + fastapi-cloud-cli==0.3.1
 + gguf==0.17.1
 + httptools==0.7.1
 + interegular==0.3.3
 - lark==1.3.0
 + lark==1.2.2
 + llguidance==0.7.30
 - llvmlite==0.43.0
 + llvmlite==0.44.0
 + lm-format-enforcer==0.11.3
 + mistral-common==1.8.5
 + msgspec==0.19.0
 + ninja==1.13.0
 - numba==0.60.0
 + numba==0.61.2
 + openai-harmony==0.0.4
 + outlines-core==0.2.11
 + partial-json-parser==0.2.1.1.post6
 + prometheus-fastapi-instrumentator==7.1.0
 - pyarrow==18.1.0
 + pyarrow==21.0.0
 + pybase64==1.4.2
 + pycountry==24.6.1
 + pydantic-extra-types==2.10.6
 + ray==2.50.1
 + rich-toolkit==0.15.1
 + rignore==0.7.1
 + setproctitle==1.3.7
 - setuptools==75.2.0
 + setuptools==79.0.1
 + shtab==1.7.2
 - torchao==0.10.0
 + torchao==0.13.0
 - transformers==4.57.1
 + transformers==4.56.2
 + trl==0.23.0
 + tyro==0.9.35
 + unsloth==2025.10.7
 + unsloth-zoo==2025.10.8
 + uvloop==0.22.1
 + vllm==0.10.2
 + watchfiles==1.1.1
 + xformers==0.0.32.post1
 + xgrammar==0.1.23
Using Python 3.12.12 environment at: /usr
Resolved 18 packages in 29ms
Prepared 2 packages in 513ms
Uninstalled 2 packages in 136ms
Installed 2 packages in 50ms
 - tokenizers==0.22.1
 + tokenizers==0.21.4
 - transformers==4.56.2
 + transformers==4.55.4
Using Python 3.12.12 environment at: /usr
Resolved 1 package in 1ms
Prepared 1 package in 33ms
Uninstalled 1 package in 2ms
Installed 1 package in 6ms
 - trl==0.23.0
 + trl==0.22.2

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [ ]:
%cd '/content/drive/MyDrive/multi-reward-math-reasoning/Llama'

/content/drive/MyDrive/multi-reward-math-reasoning/Llama

In [ ]:
%ls

 grpo_trainer_lora_model/        Llama.ipynb
 huggingface_tokenizers_cache/   unsloth_compiled_cache/
'Llama-3.2-1b outputs'/          unsloth_training_checkpoints/
 Llama-3.2-3B.ipynb              wandb/

In [ ]:
from unsloth import FastLanguageModel
from trl import SFTConfig, GRPOConfig, SFTTrainer, GRPOTrainer
from vllm import SamplingParams

import gc
import re
import time
import torch
import numpy as np
import pandas as pd

from pathlib import Path
from tqdm.notebook import tqdm
from datasets import load_dataset, Dataset
from safetensors import safe_open

from peft import LoraConfig, get_peft_model, TaskType
from transformers import (
    AutoTokenizer, AutoModelForCausalLM,
    BitsAndBytesConfig, TextStreamer
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
INFO 10-21 07:47:32 [__init__.py:216] Automatically detected platform cuda.
🦥 Unsloth Zoo will now patch everything to make training faster!

# Model Setup

In [ ]:
# Try 3B first, fallback to 1B if OOM
try:
    model_id = 'unsloth/Llama-3.2-3B'          # Attempt 3B model
    model_name = model_id.split('/')[-1].lower()
    max_seq_length = 2048
    lora_rank = 8                               # Further reduced rank for memory
    print(f"Attempting to load {model_id}")
except Exception as e:
    print(f"3B model failed, falling back to 1B: {e}")
    model_id = 'unsloth/Llama-3.2-1B'          # Fallback to 1B
    model_name = model_id.split('/')[-1].lower()
    max_seq_length = 2048
    lora_rank = 16                              # Can use higher rank with 1B

Attempting to load unsloth/Llama-3.2-3B

In [ ]:
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=model_id,
    max_seq_length=max_seq_length,
    load_in_4bit=True,          # Enable 4-bit quantization to save memory
    fast_inference=True,        # Enable vLLM fast inference
    max_lora_rank=lora_rank,
    gpu_memory_utilization=0.7, # Reduced from 0.9 to leave more headroom
)
model = FastLanguageModel.get_peft_model(
    model,
    r=lora_rank,                          # Rank: adaptation capacity (16 good for reasoning tasks)
    lora_alpha=lora_rank * 2,             # Scaling factor (typically 2x rank)
    lora_dropout=0.1,                     # Regularization to prevent overfitting
    target_modules=[                      # Reduced target modules to save memory
        'q_proj', 'k_proj', 'v_proj', 'o_proj',
        # 'gate_proj', 'up_proj', 'down_proj',  # Comment out MLP layers to save memory
    ],
    use_gradient_checkpointing='unsloth', # Reduces memory usage
    random_state=3407,
)

INFO 10-21 07:47:52 [vllm_utils.py:694] Unsloth: Patching vLLM v1 graph capture
INFO 10-21 07:47:52 [vllm_utils.py:722] Unsloth: Patching vLLM v0 graph capture
==((====))==  Unsloth 2025.10.7: Fast Llama patching. Transformers: 4.55.4. vLLM: 0.10.2.
   \\   /|    NVIDIA A100-SXM4-40GB. Num GPUs = 1. Max memory: 39.557 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.8.0+cu126. CUDA: 8.0. CUDA Toolkit: 12.6. Triton: 3.4.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.32.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: vLLM loading unsloth/llama-3.2-3b-unsloth-bnb-4bit with actual GPU utilization = 69.2%
Unsloth: Your GPU has CUDA compute capability 8.0 with VRAM = 39.56 GB.
Unsloth: Using conservativeness = 1.0. Chunked prefill tokens = 2048. Num Sequences = 320.
Unsloth: vLLM's KV Cache can use up to 24.98 GB. Also swap space = 6 GB.
WARNING 10-21 07:48:02 [compilation.py:456] full_cuda_graph is deprecated, use cudagraph_mode=FULL instead.
Unsloth: Not an error, but `device` is not supported in vLLM. Skipping.
INFO 10-21 07:48:02 [utils.py:328] non-default args: {'load_format': 'bitsandbytes', 'dtype': torch.bfloat16, 'seed': 0, 'max_model_len': 2048, 'enable_prefix_caching': True, 'swap_space': 6, 'gpu_memory_utilization': 0.6919826757536155, 'max_num_batched_tokens': 2048, 'max_num_seqs': 320, 'max_logprobs': 0, 'disable_log_stats': True, 'quantization': 'bitsandbytes', 'enable_lora': True, 'max_lora_rank': 8, 'enable_chunked_prefill': True, 'compilation_config': {"level":3,"debug_dump_path":"","cache_dir":"","backend":"inductor","custom_ops":[],"splitting_ops":null,"use_inductor":true,"compile_sizes":null,"inductor_compile_config":{"epilogue_fusion":true,"max_autotune":false,"shape_padding":true,"trace.enabled":false,"triton.cudagraphs":true,"debug":false,"dce":true,"memory_planning":true,"coordinate_descent_tuning":false,"trace.graph_diagram":false,"compile_threads":12,"group_fusion":true,"disable_progress":false,"verbose_progress":true,"triton.multi_kernel":0,"triton.use_block_ptr":true,"triton.enable_persistent_tma_matmul":true,"triton.autotune_at_compile_time":false,"triton.cooperative_reductions":false,"cuda.compile_opt_level":"-O2","cuda.enable_cuda_lto":true,"combo_kernels":false,"benchmark_combo_kernel":true,"combo_kernel_foreach_dynamic_shapes":true,"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":2,"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":null,"cudagraph_copy_inputs":false,"full_cuda_graph":true,"pass_config":{},"max_capture_size":null,"local_cache_dir":null}, 'model': 'unsloth/llama-3.2-3b-unsloth-bnb-4bit'}
INFO 10-21 07:48:21 [__init__.py:742] Resolved architecture: LlamaForCausalLM
INFO 10-21 07:48:21 [__init__.py:1815] Using max model len 2048
WARNING 10-21 07:48:22 [_ipex_ops.py:16] Import error msg: No module named 'intel_extension_for_pytorch'
INFO 10-21 07:48:24 [scheduler.py:222] Chunked prefill is enabled with max_num_batched_tokens=2048.
WARNING 10-21 07:48:24 [lora.py:92] `lora_extra_vocab_size` is deprecated and will be removed in v0.12.0. Additional vocabulary support for LoRA adapters is being phased out.
Unsloth: vLLM Bitsandbytes config using kwargs = {'load_in_8bit': False, 'load_in_4bit': True, 'bnb_4bit_compute_dtype': 'bfloat16', 'bnb_4bit_quant_storage': 'uint8', 'bnb_4bit_quant_type': 'nf4', 'bnb_4bit_use_double_quant': True, 'llm_int8_enable_fp32_cpu_offload': False, 'llm_int8_has_fp16_weight': False, 'llm_int8_skip_modules': ['lm_head', 'multi_modal_projector', 'merger', 'modality_projection', 'model.layers.1.mlp'], 'llm_int8_threshold': 6.0}

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/17.2M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/459 [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/230 [00:00<?, ?B/s]

INFO 10-21 07:48:31 [core.py:76] Initializing a V1 LLM engine (v0.10.2) with config: model='unsloth/llama-3.2-3b-unsloth-bnb-4bit', speculative_config=None, tokenizer='unsloth/llama-3.2-3b-unsloth-bnb-4bit', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=2048, download_dir=None, load_format=bitsandbytes, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=bitsandbytes, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=unsloth/llama-3.2-3b-unsloth-bnb-4bit, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"inductor","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2","vllm.mamba_mixer","vllm.short_conv","vllm.linear_attention","vllm.plamo2_mamba_mixer","vllm.gdn_attention"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"epilogue_fusion":true,"max_autotune":false,"shape_padding":true,"trace.enabled":false,"triton.cudagraphs":true,"debug":false,"dce":true,"memory_planning":true,"coordinate_descent_tuning":false,"trace.graph_diagram":false,"compile_threads":12,"group_fusion":true,"disable_progress":false,"verbose_progress":true,"triton.multi_kernel":0,"triton.use_block_ptr":true,"triton.enable_persistent_tma_matmul":true,"triton.autotune_at_compile_time":false,"triton.cooperative_reductions":false,"cuda.compile_opt_level":"-O2","cuda.enable_cuda_lto":true,"combo_kernels":false,"benchmark_combo_kernel":true,"combo_kernel_foreach_dynamic_shapes":true,"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":2,"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":true,"pass_config":{},"max_capture_size":512,"local_cache_dir":null}
INFO 10-21 07:48:32 [parallel_state.py:1165] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 10-21 07:48:32 [topk_topp_sampler.py:69] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
INFO 10-21 07:48:32 [gpu_model_runner.py:2338] Starting to load model unsloth/llama-3.2-3b-unsloth-bnb-4bit...
INFO 10-21 07:48:33 [gpu_model_runner.py:2370] Loading model from scratch...
INFO 10-21 07:48:33 [cuda.py:362] Using Flash Attention backend on V1 engine.
INFO 10-21 07:48:33 [bitsandbytes_loader.py:758] Loading weights with BitsAndBytes quantization. May take a while ...
INFO 10-21 07:48:35 [weight_utils.py:348] Using model weights format ['*.safetensors']

model.safetensors:   0%|          | 0.00/2.35G [00:00<?, ?B/s]

INFO 10-21 07:48:42 [weight_utils.py:369] Time spent downloading weights for unsloth/llama-3.2-3b-unsloth-bnb-4bit: 7.412665 seconds
INFO 10-21 07:48:43 [weight_utils.py:406] No model.safetensors.index.json found in remote.

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]

INFO 10-21 07:48:44 [punica_selector.py:19] Using PunicaWrapperGPU.
INFO 10-21 07:48:45 [gpu_model_runner.py:2392] Model loading took 2.2634 GiB and 10.942394 seconds
INFO 10-21 07:48:56 [backends.py:539] Using cache directory: /root/.cache/vllm/torch_compile_cache/637708d790/rank_0_0/backbone for vLLM's torch.compile
INFO 10-21 07:48:56 [backends.py:550] Dynamo bytecode transform time: 10.68 s

Unsloth: Compiling kernels: 100%|██████████| 7/7 [00:00<00:00, 14.76it/s, triton_poi_fused_view_6]

INFO 10-21 07:49:03 [backends.py:194] Cache the graph for dynamic shape for later use

Unsloth: Compiling kernels: 100%|██████████| 9/9 [00:00<00:00, 24.28it/s, triton_poi_fused_view_8]
Unsloth: Compiling kernels: 100%|██████████| 9/9 [00:00<00:00, 381.45it/s, triton_poi_fused_view_8]
Unsloth: Compiling kernels: 100%|██████████| 9/9 [00:00<00:00, 567.86it/s, triton_poi_fused_view_8]
Unsloth: Compiling kernels: 100%|██████████| 9/9 [00:00<00:00, 551.16it/s, triton_poi_fused_view_8]
Unsloth: Compiling kernels: 100%|██████████| 9/9 [00:00<00:00, 533.05it/s, triton_poi_fused_view_8]
Unsloth: Compiling kernels: 100%|██████████| 9/9 [00:00<00:00, 540.00it/s, triton_poi_fused_view_8]
Unsloth: Compiling kernels: 100%|██████████| 9/9 [00:00<00:00, 515.17it/s, triton_poi_fused_view_8]
Unsloth: Compiling kernels: 100%|██████████| 9/9 [00:00<00:00, 542.45it/s, triton_poi_fused_view_8]
Unsloth: Compiling kernels: 100%|██████████| 9/9 [00:00<00:00, 574.82it/s, triton_poi_fused_view_8]
Unsloth: Compiling kernels: 100%|██████████| 9/9 [00:00<00:00, 521.82it/s, triton_poi_fused_view_8]
Unsloth: Compiling kernels: 100%|██████████| 9/9 [00:00<00:00, 583.24it/s, triton_poi_fused_view_8]
Unsloth: Compiling kernels: 100%|██████████| 9/9 [00:00<00:00, 603.66it/s, triton_poi_fused_view_8]
Unsloth: Compiling kernels: 100%|██████████| 9/9 [00:00<00:00, 583.95it/s, triton_poi_fused_view_8]
Unsloth: Compiling kernels: 100%|██████████| 9/9 [00:00<00:00, 565.97it/s, triton_poi_fused_view_8]
Unsloth: Compiling kernels: 100%|██████████| 9/9 [00:00<00:00, 547.72it/s, triton_poi_fused_view_8]
Unsloth: Compiling kernels: 100%|██████████| 9/9 [00:00<00:00, 555.74it/s, triton_poi_fused_view_8]
Unsloth: Compiling kernels: 100%|██████████| 9/9 [00:00<00:00, 568.94it/s, triton_poi_fused_view_8]
Unsloth: Compiling kernels: 100%|██████████| 9/9 [00:00<00:00, 523.76it/s, triton_poi_fused_view_8]
Unsloth: Compiling kernels: 100%|██████████| 9/9 [00:00<00:00, 556.02it/s, triton_poi_fused_view_8]
Unsloth: Compiling kernels: 100%|██████████| 9/9 [00:00<00:00, 517.19it/s, triton_poi_fused_view_8]
Unsloth: Compiling kernels: 100%|██████████| 9/9 [00:00<00:00, 590.91it/s, triton_poi_fused_view_8]
Unsloth: Compiling kernels: 100%|██████████| 9/9 [00:00<00:00, 513.59it/s, triton_poi_fused_view_8]
Unsloth: Compiling kernels: 100%|██████████| 9/9 [00:00<00:00, 551.84it/s, triton_poi_fused_view_8]
Unsloth: Compiling kernels: 100%|██████████| 9/9 [00:00<00:00, 543.01it/s, triton_poi_fused_view_8]
Unsloth: Compiling kernels: 100%|██████████| 9/9 [00:00<00:00, 573.38it/s, triton_poi_fused_view_8]
Unsloth: Compiling kernels: 100%|██████████| 9/9 [00:00<00:00, 506.18it/s, triton_poi_fused_view_8]
Unsloth: Compiling kernels: 100%|██████████| 9/9 [00:00<00:00, 582.66it/s, triton_poi_fused_view_8]
Unsloth: Compiling kernels: 100%|██████████| 5/5 [00:00<00:00, 25.26it/s, triton_red_fused__to_copy_add_mean_mul_pow_rsqrt_4]

INFO 10-21 07:49:39 [backends.py:215] Compiling a graph for dynamic shape takes 41.05 s
INFO 10-21 07:49:51 [monitor.py:34] torch.compile takes 51.73 s in total
INFO 10-21 07:49:53 [gpu_worker.py:298] Available KV cache memory: 23.61 GiB
INFO 10-21 07:49:54 [kv_cache_utils.py:864] GPU KV cache size: 221,040 tokens
INFO 10-21 07:49:54 [kv_cache_utils.py:868] Maximum concurrency for 2,048 tokens per request: 107.93x
INFO 10-21 07:49:54 [vllm_utils.py:699] Unsloth: Running patched vLLM v1 `capture_model`.
WARNING 10-21 07:49:54 [gpu_model_runner.py:3258] CUDAGraphMode.FULL is not supported with FlashAttentionMetadataBuilder backend (support: AttentionCGSupport.UNIFORM_BATCH); setting cudagraph_mode=FULL_AND_PIECEWISE

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 67/67 [00:27<00:00,  2.41it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 43/43 [00:11<00:00,  3.87it/s]

INFO 10-21 07:50:33 [gpu_model_runner.py:3118] Graph capturing finished in 39 secs, took 1.85 GiB
INFO 10-21 07:50:33 [vllm_utils.py:706] Unsloth: Patched vLLM v1 graph capture finished in 39 secs.

INFO 10-21 07:50:35 [gpu_worker.py:391] Free memory on device (39.03/39.56 GiB) on startup. Desired GPU memory utilization is (0.6919826757536155, 27.37 GiB). Actual usage is 2.26 GiB for weight, 1.48 GiB for peak activation, 0.02 GiB for non-torch memory, and 1.85 GiB for CUDAGraph memory. Replace gpu_memory_utilization config with `--kv-cache-memory=23212828979` to fit into requested memory, or `--kv-cache-memory=35729536512` to fully utilize gpu memory. Current kv cache memory in use is 25351924019 bytes.
INFO 10-21 07:50:35 [core.py:218] init engine (profile, create kv cache, warmup model) took 110.11 seconds
INFO 10-21 07:50:37 [llm.py:295] Supported_tasks: ('generate',)
INFO 10-21 07:50:37 [__init__.py:36] No IOProcessor plugins requested by the model
Unsloth: Just some info: will skip parsing ['pre_feedforward_layernorm', 'layer_norm2', 'norm2', 'norm1', 'input_layernorm', 'post_layernorm', 'post_attention_layernorm', 'post_feedforward_layernorm', 'q_norm', 'ffn_norm', 'layer_norm1', 'k_norm', 'attention_norm']
Unsloth: Just some info: will skip parsing ['pre_feedforward_layernorm', 'layer_norm2', 'norm2', 'norm1', 'cross_attn_input_layernorm', 'input_layernorm', 'post_layernorm', 'post_attention_layernorm', 'cross_attn_post_attention_layernorm', 'post_feedforward_layernorm', 'q_norm', 'ffn_norm', 'layer_norm1', 'k_norm', 'attention_norm']

tokenizer_config.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/459 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.2M [00:00<?, ?B/s]

Unsloth: Dropout = 0 is supported for fast patching. You are using dropout = 0.1.
Unsloth will patch all other layers, except LoRA matrices, causing a performance hit.
Unsloth 2025.10.7 patched 28 layers with 0 QKV layers, 0 O layers and 0 MLP layers.

# Chat Template

In [ ]:
# Define structured output format for mathematical reasoning
REASONING_START = '<THINK>'   # Begin reasoning section
REASONING_END = '</THINK>'    # End reasoning section
SOLUTION_START = '<SOLUTION>' # Begin final answer
SOLUTION_END = '</SOLUTION>'  # End final answer

# System prompt that teaches the model our desired reasoning structure
SYSTEM_PROMPT = f'''You are a mathematical reasoning assistant. When given a math problem:
1. Show your step-by-step work between {REASONING_START} and {REASONING_END}.
2. Provide your final numerical answer between {SOLUTION_START} and {SOLUTION_END}.
3. Be precise and show all calculation steps clearly.'''
print(SYSTEM_PROMPT)

You are a mathematical reasoning assistant. When given a math problem:
1. Show your step-by-step work between <THINK> and </THINK>.
2. Provide your final numerical answer between <SOLUTION> and </SOLUTION>.
3. Be precise and show all calculation steps clearly.

In [ ]:
chat_template = ( # Build and assign chat_template to the tokenizer
    # If the very first message is a SYSTEM role, print it + <eos>:
    "{% if messages[0]['role'] == 'system' %}"
      "{{ messages[0]['content'] + eos_token }}"
      "{% set loop_messages = messages[1:] %}"
    "{% else %}"
      # Otherwise, inject our system_prompt + <eos>:
      "{{ '{system_prompt}' + eos_token }}"
      "{% set loop_messages = messages %}"
    "{% endif %}"

    # Now loop over the remaining messages (either user or assistant):
    "{% for message in loop_messages %}"
      "{% if message['role'] == 'user' %}"
        "{{ message['content'] }}"
      "{% elif message['role'] == 'assistant' %}"
        "{{ message['content'] + eos_token }}"
      "{% endif %}"
    "{% endfor %}"

    # If we asked for "add_generation_prompt", append <REASONING> to the end:
    "{% if add_generation_prompt %}{{ '{reasoning_start}' }}"
    "{% endif %}"
)
# Replace with out specific template:
tokenizer.chat_template = chat_template\
    .replace("'{system_prompt}'",   f"'{SYSTEM_PROMPT}'")\
    .replace("'{reasoning_start}'", f"'{REASONING_START}'")

In [ ]:
example_messages = [ # Quick sanity check of the template
    {'role': 'user', 'content': 'Which country has the highest population density?'},
    {'role': 'assistant', 'content': (
        f'{REASONING_START}'
        'I know that country X is small in area but has a huge population, '
        'so its people per square kilometer is extremely high.'
        f'{REASONING_END}{SOLUTION_START}Monaco{SOLUTION_END}'
    )},
    {'role': 'user', 'content': 'Which planet is farthest from the Sun?'},
]
print(tokenizer.apply_chat_template(example_messages, tokenize=False, add_generation_prompt=True))

You are a mathematical reasoning assistant. When given a math problem:
1. Show your step-by-step work between <THINK> and </THINK>.
2. Provide your final numerical answer between <SOLUTION> and </SOLUTION>.
3. Be precise and show all calculation steps clearly.<|end_of_text|>Which country has the highest population density?<THINK>I know that country X is small in area but has a huge population, so its people per square kilometer is extremely high.</THINK><SOLUTION>Monaco</SOLUTION><|end_of_text|>Which planet is farthest from the Sun?<THINK>

# Pre Fine-tuning (SFT)

## Data preparation

In [ ]:
# Use a subset of NVIDIA's Open Math Reasoning dataset, which was filtered to only include high quality DeepSeek R1 traces
sft_dataset = load_dataset('unsloth/OpenMathReasoning-mini', split='cot').to_pandas()
sft_dataset = sft_dataset[['expected_answer', 'problem', 'generated_solution']]

# Try converting to number - if not, replace with NaN
is_number = pd.to_numeric(pd.Series(sft_dataset['expected_answer']), errors='coerce').notnull()
sft_dataset = sft_dataset.iloc[np.where(is_number)[0]] # Select only numbers
sft_dataset

README.md:   0%|          | 0.00/603 [00:00<?, ?B/s]

data/cot-00000-of-00001.parquet:   0%|          | 0.00/106M [00:00<?, ?B/s]

Generating cot split:   0%|          | 0/19252 [00:00<?, ? examples/s]

,expected_answer,problem,generated_solution
0,14,Given $\sqrt{x^2+165}-\sqrt{x^2-52}=7$ and $x$...,"<think>\nOkay, let's see. I need to solve the ..."
6,-2,Find the value of the parameter $a$ for which ...,"<think>\nOkay, so I need to find the value of ..."
9,18,What is the sum of all real numbers $x$ for wh...,"<think>\nOkay, so I need to solve the equation..."
13,2,Evaluate the sum \(\sum_{n=1}^\infty \frac{\ph...,"<think>\nOkay, so I need to evaluate the infin..."
17,30,What is the largest positive integer that divi...,"<think>\nAlright, so I need to find the larges..."
...,...,...,...
19243,244,"Let \( p \), \( q \), and \( r \) be the disti...","<think>\nOkay, so I need to find the value of ..."
19245,1,A bug is on the $0$ of a number line. At any p...,"<think>\nOkay, so I have this problem where a ..."
19247,4,A bus left point X for point Y. Two hours late...,"<think>\nOkay, let's tackle this problem step ..."
19248,18,Each interior angle of a regular n-gon measure...,"<think>\nOkay, let's see. I need to find the n..."
19250,0.8960,Find the probability that the second blue resu...,"<think>\nOkay, so I need to find the probabili..."

In [ ]:
def format_dataset(x): # Format the dataset to follow our GRPO style formatting
    expected_answer = x['expected_answer']
    problem = x['problem']

    # Remove generated <think> and </think>
    thoughts = x['generated_solution'].replace('<think>', '').replace('</think>', '')
    thoughts = thoughts.strip()

    # Add our custom formatting
    final_prompt = REASONING_START + thoughts + REASONING_END + \
                   SOLUTION_START + expected_answer + SOLUTION_END
    return [
        {'role': 'system'   , 'content': SYSTEM_PROMPT},
        {'role': 'user'     , 'content': problem},
        {'role': 'assistant', 'content': final_prompt},
    ]

sft_dataset['messages'] = sft_dataset.apply(format_dataset, axis=1)
print(tokenizer.apply_chat_template(sft_dataset['messages'][0], tokenize=False))

You are a mathematical reasoning assistant. When given a math problem:
1. Show your step-by-step work between <THINK> and </THINK>.
2. Provide your final numerical answer between <SOLUTION> and </SOLUTION>.
3. Be precise and show all calculation steps clearly.<|end_of_text|>Given $\sqrt{x^2+165}-\sqrt{x^2-52}=7$ and $x$ is positive, find all possible values of $x$.<THINK>Okay, let's see. I need to solve the equation √(x² + 165) - √(x² - 52) = 7, and find all positive values of x. Hmm, radicals can be tricky, but maybe if I can eliminate the square roots by squaring both sides. Let me try that.

First, let me write down the equation again to make sure I have it right:

√(x² + 165) - √(x² - 52) = 7.

Okay, so the idea is to isolate one of the radicals and then square both sides. Let me try moving the second radical to the other side:

√(x² + 165) = 7 + √(x² - 52).

Now, if I square both sides, maybe I can get rid of the square roots. Let's do that:

(√(x² + 165))² = (7 + √(x² - 52))².

Simplifying the left side:

x² + 165 = 49 + 14√(x² - 52) + (√(x² - 52))².

The right side is expanded using the formula (a + b)² = a² + 2ab + b². So the right side becomes 7² + 2*7*√(x² - 52) + (√(x² - 52))², which is 49 + 14√(x² - 52) + (x² - 52).

So putting it all together:

x² + 165 = 49 + 14√(x² - 52) + x² - 52.

Hmm, let's simplify the right side. The x² terms will cancel out, right? Let's subtract x² from both sides:

165 = 49 + 14√(x² - 52) - 52.

Simplify the constants on the right:

49 - 52 is -3, so:

165 = -3 + 14√(x² - 52).

Now, add 3 to both sides to isolate the radical term:

165 + 3 = 14√(x² - 52).

So 168 = 14√(x² - 52).

Divide both sides by 14:

168 / 14 = √(x² - 52).

12 = √(x² - 52).

Now, square both sides again to eliminate the square root:

12² = x² - 52.

144 = x² - 52.

Add 52 to both sides:

144 + 52 = x².

196 = x².

So x = √196 = 14.

But wait, since the problem states that x is positive, we only take the positive root. So x = 14.

But hold on, when dealing with squaring equations, sometimes extraneous solutions can come up. I should check if this solution actually satisfies the original equation.

Let's plug x = 14 back into the original equation:

√(14² + 165) - √(14² - 52) = ?

Calculate each term:

14² is 196.

So first radical: √(196 + 165) = √361 = 19.

Second radical: √(196 - 52) = √144 = 12.

So 19 - 12 = 7, which is exactly the right-hand side. So yes, it checks out.

Therefore, the only solution is x = 14. Since the problem says x is positive, we don't have to consider negative roots. So I think that's the answer.
To solve the equation \(\sqrt{x^2 + 165} - \sqrt{x^2 - 52} = 7\) for positive \(x\), we proceed as follows:

1. Start with the given equation:
   \[
   \sqrt{x^2 + 165} - \sqrt{x^2 - 52} = 7
   \]

2. Isolate one of the square roots by moving \(\sqrt{x^2 - 52}\) to the right side:
   \[
   \sqrt{x^2 + 165} = 7 + \sqrt{x^2 - 52}
   \]

3. Square both sides to eliminate the square root on the left:
   \[
   (\sqrt{x^2 + 165})^2 = (7 + \sqrt{x^2 - 52})^2
   \]
   Simplifying both sides, we get:
   \[
   x^2 + 165 = 49 + 14\sqrt{x^2 - 52} + (x^2 - 52)
   \]

4. Combine like terms on the right side:
   \[
   x^2 + 165 = x^2 - 52 + 49 + 14\sqrt{x^2 - 52}
   \]
   Simplifying further:
   \[
   x^2 + 165 = x^2 - 3 + 14\sqrt{x^2 - 52}
   \]

5. Subtract \(x^2\) from both sides:
   \[
   165 = -3 + 14\sqrt{x^2 - 52}
   \]

6. Add 3 to both sides to isolate the term with the square root:
   \[
   168 = 14\sqrt{x^2 - 52}
   \]

7. Divide both sides by 14:
   \[
   12 = \sqrt{x^2 - 52}
   \]

8. Square both sides again to eliminate the square root:
   \[
   12^2 = x^2 - 52
   \]
   Simplifying:
   \[
   144 = x^2 - 52
   \]

9. Add 52 to both sides to solve for \(x^2\):
   \[
   196 = x^2
   \]

10. Take the positive square root (since \(x\) is positive):
    \[
    x = \sqrt{196} = 14
    \]

11. Verify the solution by substituting \(x = 14\) back into the original equation:
    \[
    \sqrt{14^2 + 165} - \sqrt{14^2 - 52} = \sqrt{196 + 165} - \sqrt{196 - 52} = \sqrt{361} - \sqrt{144} = 19 - 12 = 7
    \]
    The solution checks out.

Thus, the only positive solution is:
\[
\boxed{14}
\]</THINK><SOLUTION>14</SOLUTION><|end_of_text|>

In [ ]:
# Truncate pre fine-tuning sft_dataset to max_seq_length / 2 since we don't want too long reasoning traces
sft_dataset['seq_length'] = sft_dataset['messages'].apply(lambda x: len(tokenizer.apply_chat_template(x)))
print('Token-length percentiles (50/90/99):', np.percentile(sft_dataset['seq_length'], [50, 90, 99]))

threshold = max_seq_length / 2
sft_dataset_filtered = sft_dataset.loc[sft_dataset['seq_length'] <= threshold].copy()
print(f'Remaining for training (<= {threshold} tokens): {len(sft_dataset_filtered)}/{len(sft_dataset)}')

sft_dataset_filtered['text'] = tokenizer.apply_chat_template(sft_dataset_filtered['messages'].values.tolist(), tokenize=False)
sft_dataset_filtered = Dataset.from_pandas(sft_dataset_filtered)
sft_dataset_filtered

Token-length percentiles (50/90/99): [ 3469.   8310.4 14578.9]
Remaining for training (<= 1024.0 tokens): 73/7507

Dataset({
    features: ['expected_answer', 'problem', 'generated_solution', 'messages', 'seq_length', 'text', '__index_level_0__'],
    num_rows: 73
})

## Pre fine-tune to understand custom GRPO formatting

In [ ]:
trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=sft_dataset_filtered,
    args=SFTConfig(
        dataset_text_field='text',
        num_train_epochs=3,
        per_device_train_batch_size=1,
        gradient_accumulation_steps=1,
        optim='adamw_8bit',
        weight_decay=0.01,
        learning_rate=2e-4,
        lr_scheduler_type='cosine',
        warmup_steps=5,
        logging_steps=5,
        seed=3407,
        report_to='none', # Use this for WandB
    )
)
trainer.train()

Unsloth: Tokenizing ["text"] (num_proc=16):   0%|          | 0/73 [00:00<?, ? examples/s]

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 73 | Num Epochs = 3 | Total steps = 219
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 1
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 1 x 1) = 1
 "-____-"     Trainable parameters = 4,587,520 of 3,217,337,344 (0.14% trained)

Unsloth: Will smartly offload gradients to save VRAM!

TrainOutput(global_step=219, training_loss=0.7088047195242965, metrics={'train_runtime': 114.3662, 'train_samples_per_second': 1.915, 'train_steps_per_second': 1.915, 'total_flos': 3348430032273408.0, 'train_loss': 0.7088047195242965, 'epoch': 3.0})

## Check if model has learnt to follow the format

In [ ]:
text = tokenizer.apply_chat_template( # Render into a single string and append <REASONING> for generation
    sft_dataset_filtered[1]['messages'][:2],
    tokenize=False, add_generation_prompt=True, # Append the final <REASONING>
)
_ = model.generate(
    **tokenizer(text, return_tensors='pt').to('cuda'),
    temperature=0, max_new_tokens=1024,
    streamer=TextStreamer(tokenizer, skip_prompt=False), # Stream the model's generations (CoT + solution)
)

<|begin_of_text|>You are a mathematical reasoning assistant. When given a math problem:
1. Show your step-by-step work between <THINK> and </THINK>.
2. Provide your final numerical answer between <SOLUTION> and </SOLUTION>.
3. Be precise and show all calculation steps clearly.<|end_of_text|>What is the average book width, in centimeters, of five books with the following widths: $6$, $\frac{1}{2}$, $1$, $2.5$, and $10$?<THINK>Okay, let's see. I need to find the average width of five books with widths 6, 1/2, 1, 2.5, and 10 centimeters. Hmm, average. Let me think. Average is the sum of all the values divided by the number of values. So, the sum of these five widths would be 6 + 1/2 + 1 + 2.5 + 10. Let me add them up.

6 + 1/2 is 6.5. Then 6.5 + 1 is 7.5. Then 7.5 + 2.5 is 10. Then 10 + 10 is 20. So the sum is 20 centimeters.

Now, the average is 20 divided by 5, which is 20 divided by 5. Let me calculate that. 20 divided by 5 is 4. So the average width is 4 centimeters. Wait, but let me check if I did the addition right. Let me go back. 6 + 1/2 is 6.5. Then 6.5 + 1 is 7.5. Then 7.5 + 2.5 is 10. Then 10 + 10 is 20. Yep, that's correct. So the average is 20 divided by 5, which is 4. So the answer should be 4 centimeters. Let me just make sure I didn't make a mistake. The problem says "average book width". So the average of the widths of five books. The sum is 20, divided by 5, which is 4. That seems right. I think that's it.
To find the average width of five books with widths 6, 1/2, 1, 2.5, and 10 centimeters, we start by adding up all the widths:

\[
6 + \frac{1}{2} + 1 + 2.5 + 10
\]

First, we simplify the addition by combining like terms:

\[
6 + \frac{1}{2} = 6 + 0.5 = 6.5
\]

Next, we add 6.5 and 1:

\[
6.5 + 1 = 7.5
\]

Then, we add 7.5 and 2.5:

\[
7.5 + 2.5 = 10
\]

Finally, we add 10 and 10:

\[
10 + 10 = 20
\]

Thus, the sum of the widths is:

\[
20 \text{ centimeters}
\]

Next, we calculate the average width by dividing the sum by the number of widths:

\[
\frac{20}{5} = 4 \text{ centimeters}
\]

Therefore, the average width of the five books is:

\[
\boxed{4} \text{ centimeters}
\]</THINK><SOLUTION>4</SOLUTION><|end_of_text|>

In [ ]:
del sft_dataset, sft_dataset_filtered
gc.collect()
torch.cuda.empty_cache()

# Post Fine-tuning (RL)

## Data preparation

In [ ]:
def process_dataset_sample(example): # Convert GSM8K example to conversation format for GRPO training
    return {
        'prompt': [ # Create conversation with system prompt for structured reasoning
            {'role': 'system', 'content': SYSTEM_PROMPT},
            {'role': 'user', 'content': example['question']},
        ],
        # Extract numerical answer from GSM8K format ('Explanation... #### 42') as Ground truth for reward functions
        'answer': example['answer'].split('####')[1].strip() if '####' in example['answer'] else None
    }

In [ ]:
# train_dataset = load_dataset('openai/gsm8k', 'main', split=['train[:10%]'])
train_dataset = load_dataset('openai/gsm8k', 'main', split='train')
train_dataset = train_dataset.map(process_dataset_sample)

print(f'Training samples: {len(train_dataset):,}\n'
      f"- Sample question: {train_dataset[0]['prompt'][1]['content']}\n"
      f"- Sample answer (ground truth for rewards): {train_dataset[0]['answer']}\n"
      f"- Prompt (system + user):\n{train_dataset[0]['prompt']}")

README.md: 0.00B [00:00, ?B/s]

main/train-00000-of-00001.parquet:   0%|          | 0.00/2.31M [00:00<?, ?B/s]

main/test-00000-of-00001.parquet:   0%|          | 0.00/419k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/7473 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1319 [00:00<?, ? examples/s]

Map:   0%|          | 0/7473 [00:00<?, ? examples/s]

Training samples: 7,473
- Sample question: Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May?
- Sample answer (ground truth for rewards): 72
- Prompt (system + user):
[{'content': 'You are a mathematical reasoning assistant. When given a math problem:\n1. Show your step-by-step work between <THINK> and </THINK>.\n2. Provide your final numerical answer between <SOLUTION> and </SOLUTION>.\n3. Be precise and show all calculation steps clearly.', 'role': 'system'}, {'content': 'Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May?', 'role': 'user'}]

In [ ]:
# Get the top 90% prompt length so we don't accidentally truncate them, i.e. we'll remove the top 10% long prompts
tokenized_dataset = train_dataset.map(
    lambda x: {'tokens': tokenizer.apply_chat_template(x['prompt'], add_generation_prompt=True, tokenize=True)},
    batched=True,
).map(lambda x: {'length': len(x['tokens'])})
print(tokenizer.decode(tokenized_dataset[0]['tokens']))

thresholds = np.percentile(tokenized_dataset['length'], [50, 90, 99])
max_prompt_length = int(thresholds[1])
print('Token-length percentiles (50/90/99):', thresholds, '=> Choose max_prompt_length =', max_prompt_length)

# Filter only samples smaller than 90% max length
train_dataset = train_dataset.select(np.where(np.array(tokenized_dataset['length']) <= max_prompt_length)[0])
print(f'Remaining for training (<= {max_prompt_length} tokens): {len(train_dataset)}/{len(tokenized_dataset)}')
del tokenized_dataset

Map:   0%|          | 0/7473 [00:00<?, ? examples/s]

Map:   0%|          | 0/7473 [00:00<?, ? examples/s]

You are a mathematical reasoning assistant. When given a math problem:
1. Show your step-by-step work between <THINK> and </THINK>.
2. Provide your final numerical answer between <SOLUTION> and </SOLUTION>.
3. Be precise and show all calculation steps clearly.<|end_of_text|>Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May?<THINK>
Token-length percentiles (50/90/99): [116. 149. 187.] => Choose max_prompt_length = 149
Remaining for training (<= 149 tokens): 6749/7473

## Regex Patterns

In [ ]:
# Match the reasoning sections and answers
match_format = re.compile(
    # rf'^[\s]{{0,}}'                                     # Optional whitespace at start
    # rf'{REASONING_START}.+?{REASONING_END}.*?'          # Reasoning section (non-greedy)
    rf'{REASONING_END}.*?'                              # We always prepend REASONING_START
    rf'{SOLUTION_START}(.+?){SOLUTION_END}'             # Solution section with capture group
    rf'[\s]{{0,}}(?:{re.escape(tokenizer.eos_token)})?' # Add optional EOS token matching
    rf'[\s]{{0,}}$',                                    # Optional whitespace at end
    flags=re.MULTILINE | re.DOTALL,                     # Multi-line matching with . matching newlines
)
match_format.findall( # Verify it works
    f'{REASONING_START}Let me think!{REASONING_END}'\
    f'{SOLUTION_START}\n2\n{SOLUTION_END}\n\n',
)

['\n2\n']

In [ ]:
# Sometimes it might not be 1 number as the answer, but like a sentence.
# For example: 'The solution is $20' -> we extract 20
# We also remove possible commas for example as in 123,456
match_number = re.compile(
    rf'{SOLUTION_START}.*?[\s]{{0,}}([-]?[\d\.\,]{{1,}})', # Extract numbers from solution section
    flags=re.MULTILINE | re.DOTALL | re.IGNORECASE,        # Flexible pattern matching
)
print(match_number.findall('<SOLUTION>  0.34  </SOLUTION>'))
print(match_number.findall('<SOLUTION>  123,456  </SOLUTION>'))
print(match_number.findall('<SOLUTION>  -0.234  </SOLUTION>'))
print(match_number.findall('<SOLUTION>17</SOLUTION>'))

['0.34']
['123,456']
['-0.234']
['17']

## Multi-reward design

In [ ]:
def match_format_strictly(completions, **kwargs) -> list[float]:
    ''' Reward Function 1: Exact Format Compliance
    High reward (3.0) for perfect format adherence
    Ensures model learns the complete structured output pattern
    '''
    return [
        3.0 if match_format.search(completion[0]['content']) else 0.0
        for completion in completions
    ]

In [ ]:
# If it fails, reward the model if it at least follows the format partially, by counting each symbol
def match_format_softly(completions, **kwargs) -> list[float]:
    ''' Reward Function 2: Partial Format Credit
    Graduated scoring for format elements
    Encourages learning individual components even if not perfect
    '''
    rewards = []
    for completion in completions:
        reward = 0
        response = completion[0]['content']

        # Count how many keywords are seen - we penalize if too many!
        # Award +0.5 for correct token count, -0.5 for wrong count
        # No need to reward REASONING_START since we always prepend it!
        # reward += 0.5 if response.count(REASONING_START) == 1 else -0.5
        reward += 0.5 if response.count(REASONING_END) == 1 else -0.5
        reward += 0.5 if response.count(SOLUTION_START) == 1 else -0.5
        reward += 0.5 if response.count(SOLUTION_END) == 1 else -0.5
        rewards.append(reward)
    return rewards

In [ ]:
# Extract the generated answer, and reward or penalize it
def check_answer_correctness(completions, answer, **kwargs) -> list[float]:
    ''' Reward Function 3: Graduated scoring for mathematical accuracy
    - 5.0: Exact string match gets full points
    - 2.0: Within 10% (close answer)
    - 1.5: Within 20% (reasonable attempt)
    - -2.5: Wrong answer (penalty for incorrect math)
    '''
    responses = [completion[0]['content'] for completion in completions]
    extracted_responses = [ # Extract answers using format pattern
        guess.group(1) if (guess := match_format.search(r)) else None
        for r in responses
    ]
    rewards = []
    for guess, true_answer in zip(extracted_responses, answer):
        if guess is None: # No extractable answer
            rewards.append(-2.0)
            continue

        if guess == true_answer: rewards.append(5.0)                   # Correct answer gets 5 points!
        elif guess.strip() == true_answer.strip(): rewards.append(3.5) # Match if spaces are seen, but less reward
        else: # Try numerical comparison for partial credit
            try: # We also reward it based on how close the answer is to the true one via ratios
                ratio = float(guess) / float(true_answer)     # If the answer is within some range, reward it!
                if 0.9 <= ratio <= 1.1: rewards.append(2.0)   # Within 10%
                elif 0.8 <= ratio <= 1.2: rewards.append(1.5) # Within 20%
                else: rewards.append(-2.5)                    # Penalize wrong answers
            except (ValueError, ZeroDivisionError):
                rewards.append(-4.5)                          # Invalid numerical format
    return rewards

In [ ]:
def check_numbers_extraction(prompts, completions, answer, **kwargs) -> list[float]:
    ''' Reward Function 4: Number Extraction Ability
    Tests the model's ability to extract numerical values from solution sections
    Complementary to exact format matching - focuses on parsing capability
    '''
    question = prompts[0][-1]['content'] # Exclude system prompt
    responses = [completion[0]['content'] for completion in completions]

    extracted_responses = [ # Extract numbers from solution sections using number pattern
        guess.group(1) if (guess := match_number.search(r)) else None
        for r in responses
    ]
    rewards = []

    # Print only every few steps
    check_numbers_extraction.counter = getattr(check_numbers_extraction, 'counter', 0) + 1
    if check_numbers_extraction.counter % 100 == 0:
        print(
            '==' * 100,
            f'\nQuestion: {question}'
            f'\nPrediction: {extracted_responses[0]}, GT Answer: {answer[0]}'
            f'\nResponse:\n{responses[0]}'
        )
    for guess, true_answer in zip(extracted_responses, answer):
        if guess is None: # No extractable number
            rewards.append(-2.5)
            continue

        try: # Simple numerical equality check
            true_val = float(true_answer.strip())             # Convert to numbers
            guess_val = float(guess.strip().replace(',', '')) # Remove commas like in 123,456
            rewards.append(3.5 if guess_val == true_val else -1.5)
        except (ValueError, TypeError):
            rewards.append(0) # Invalid number format
    return rewards

## GRPO training setup

In [ ]:
max_prompt_length = 152 + 1 # + 1 just in case!
max_completion_length = max_seq_length - max_prompt_length
vllm_sampling_params = SamplingParams(
    min_p = 0.1,
    top_p = 1.0,
    top_k = -1,
    stop = [tokenizer.eos_token],
    include_stop_str_in_output = True,
)

In [ ]:
training_args = GRPOConfig(          # Configure GRPO training parameters for mathematical reasoning
    output_dir=f'/tmp/{model_name}', # Directory for checkpoints and logs
    vllm_sampling_params=vllm_sampling_params,
    # Training speed control
    num_train_epochs=1,              # Total number of training epochs
    per_device_train_batch_size=1,   # Keep at 1 for 3B model
    gradient_accumulation_steps=8,   # Reduced from 16 to 8 for memory
    # Computing the loss: https://huggingface.co/docs/trl/main/grpo_trainer#computing-the-loss
    scale_rewards='batch',           # Calculate mean at local/group level and std at global/batch level enables more robust reward shaping
    loss_type='dr_grpo',             # Fully remove response length bias, dividing by a constant instead of the sequence length
    # Precision & Optimization
    optim='adamw_8bit',              # adamw_torch_fused, adamw_8bit, paged_adamw_8bit
    weight_decay=0.1,                # Regularization
    max_grad_norm=0.1,               # Aggressive gradient clipping for stable training
    gradient_checkpointing=True,
    bf16=torch.cuda.is_available(),  # Enable mixed-precision training if a CUDA GPU is available (faster, less memory)
    # Learning rate scheduling
    learning_rate=1e-5,              # Conservative LR to prevent destabilizing reasoning
    warmup_ratio=0.1,
    lr_scheduler_type='cosine_with_min_lr',
    lr_scheduler_kwargs=dict(min_lr=1e-6),
    # Generation control - REDUCED FOR MEMORY
    temperature=1.0,
    num_generations=2,                           # Reduced from 2 to 1 to save memory
    max_prompt_length=max_prompt_length,         # Default: 512. Sufficient for complex word problems
    max_completion_length=max_completion_length, # Default: 256. Room for detailed step-by-step reasoning
    # Reporting and saving
    report_to='wandb',
    logging_steps=10,
    logging_strategy='steps',
    save_total_limit=1,
    # max_steps=100,                               # TEMPORARY: Limit steps for testing
    # For optional evaluation
    # per_device_eval_batch_size=4,
    # bf16_full_eval=torch.cuda.is_available(),
    # eval_strategy='steps',                       # Evaluate after each epoch
    # load_best_model_at_end=True,                 # Load the best model based on validation loss
)

Unsloth: We now expect `per_device_train_batch_size` to be a multiple of `num_generations`.
We will change the batch size of 1 to the `num_generations` of 2

## Train the model

In [ ]:
# Memory management and cleanup before training
import gc
import torch

# Clear any existing cache
torch.cuda.empty_cache()
gc.collect()

# Set CUDA memory allocation configuration for better memory management
import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

# Check current memory usage
print(f"GPU Memory before training:")
print(f"  Allocated: {torch.cuda.memory_allocated()/1024**3:.2f} GB")
print(f"  Reserved: {torch.cuda.memory_reserved()/1024**3:.2f} GB")
print(f"  Free: {torch.cuda.get_device_properties(0).total_memory/1024**3 - torch.cuda.memory_reserved()/1024**3:.2f} GB")

GPU Memory before training:
  Allocated: 26.12 GB
  Reserved: 26.37 GB
  Free: 13.19 GB

In [ ]:
%%time
trainer = GRPOTrainer(            # Initialize GRPO trainer with multi-reward system
    model=model,                  # LoRA-adapted quantized model
    processing_class=tokenizer,
    train_dataset=train_dataset,  # Processed GSM8K dataset
    args=training_args,           # Training configuration
    reward_funcs=[                # 4 complementary reward functions
        match_format_strictly,    # Perfect structure compliance
        match_format_softly,      # Partial format credit
        check_answer_correctness, # Mathematical accuracy
        check_numbers_extraction, # Number parsing ability
    ]
)
trainer.train()
trainer.save_model(f'./{model_name}_grpo')

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 6,749 | Num Epochs = 1 | Total steps = 843
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 8 x 1) = 16
 "-____-"     Trainable parameters = 4,587,520 of 3,217,337,344 (0.14% trained)
/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: walteryeyint (walteryeyint-university-of-technology-) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

wandb: Detected [huggingface_hub.inference, openai] in use.
wandb: Use W&B Weave for improved LLM call tracing. Install Weave with `pip install weave` then add `import weave` to the top of your script.
wandb: For more information, check out the docs at: https://weave-docs.wandb.ai/

========================================================================================================================================================================================================
Question: The tallest building in the world is 100 feet tall.  If the second tallest is half that tall, and the third tallest is half as tall as the second, and the fourth is one-fifth as tall as the third, how tall are all 4 buildings put together?
Prediction: 185, GT Answer: 180
Response:
Okay, let's see. The problem said that the tallest building is 100 feet tall. The next tallest one is half that, then the next one is half as tall as the second, and the fourth one is one-fifth as tall as the third. Hmm, I need to find the total height of all four buildings. So first, let's start by breaking this down step by step.

First, the tallest building is 100 feet tall. That's building #1. The second tallest building is half that, which is 50 feet. Building #2. The third tallest is half as tall as building 2, so 25 feet. Building #3. Then the fourth tallest is one-fifth as tall as building 3, which is 10 feet tall. Building #4.

So now I need to add up the heights of all these buildings. Start adding from the bottom. Building 4 is 10 feet, building 3 is 25 feet, building 2 is 50 feet, and building 1 is 100 feet. Let's add them. Adding 10, then 25, then 50, then 100. Oh, wait, wait, let me confirm. Originally, the tallest was 100, then 50, then 25, then 10? Right. Adding 10 plus 25, that's 35, then 35 plus 50 is 85, then 85 plus 100 is 185. But wait, the problem doesn't say "buildings 1, 2, 3, 4 add up to be 185 feet tall". It says "all 4 buildings combined are 185 feet tall". So maybe I either added them in the wrong order or forgot a step. Let me backtrack.

Alternatively, starting from the top. The tallest is 100 feet, then half as tall is 50, then half that is 25, then one-fifth as tall as 25 is 5 feet. Adding those. 100, then 50, then 25, then 5. 100 + 50 + 25 + 5? Let's see. 50 + 25 = 75, then 75 + 5 = 80 feet. No, still too low. So 100 feet initially, then 50, then 25, then 5. That's 130 feet. Let me double-check the problem again. The next line says "... then the third is half as tall as the second,...". So the second one is 25 feet, not 50. So the first two are 100 feet, then 25 feet. Then 10 feet, making it 130 feet. So yes, those add up. 100 + 25 + 10 = 135 feet. So the tallest is 100, then 50, then 25, then 10, and total is 135 feet.

Wait, just to make sure I didn't miss any intermediate steps. Let me go through the problem again. The tall one is 100 feet. The second is half that, which is 50. Then the third is half of that, which is 25. Then the fourth is one-fifth of that, which is 10. So first 100 + 50. Then 100 + 25. Then 100 + 10. Yes, that's 165 feet. Then add 10 more. 165 + 10. 175 feet. Wait, but the problem says "all 4 buildings combined" but the text follows the order building 1, 2, 3, 4. So should be 100 + 50 + 25 + 10, right? That's 185 feet. So 130 plus 55. 130 + 50 is 180, then 180 + 25 is 205, then 205 + 10 is 215 feet. Yep, that agrees. So 100 + 50 is 150, then 150 + 25 is 175, then 175 + 10 is 185 feet. So all 4 together is 185.

So I think the answer should be 185. Let me just make sure I didn't mix up the numbers or times differently in my head. The problem clearly specifies each step. So first, the tallest is 100, then the second is half that, then the next one is half as tall as the second. Then the fourth is one-fifth of the third. So the second is 50, then the third is 25, and the fourth is 10. Adding those in the right order: 100 + 50 + 25 + 10. 100 + 25 + 10. Then 100 + 10 gives 110, then 110 + 25 is 135. No, that should be 100 + 50 + 25 + 10. 100 + 50 is 150, then 150 + 25 is 175, then 175 + 10 is 185. So all four together is 185. Yes, that's it. I think that's it. So the answer should be 185. Let me check again. Is there anything after that? If yes, for example, "Then the lowest is one-seventh that high." The problem only mentions fourth and fourth is one-fifth of third, which is 10 feet. That's the last part. Then add all the others: 100 + 50 + 25 + 10. So yes, 185 is the answer. Should be correct.
To find the total height of all four buildings, we start by breaking down the information given in the problem:
1. The tallest building is 100 feet tall.
2. The second tallest building is half the height of the first.
3. The third tallest building is half the height of the second.
4. The fourth tallest building is one-fifth the height of the third.

We determine the height of each building in step 1, 2, 3, and 4 sequentially, in the order described:
1. The tallest building is 100 feet tall.
2. The second tallest is half (50 feet) the height of the first.
3. The third tallest is half the height of the second (25 feet).
4. The fourth tallest is one-fifth the height of the third (10 feet).

We then sum the heights of all four buildings to find the total height:
\[
\text{Total height} = 100 \text{ feet} + 50 \text{ feet} + 25 \text{ feet} + 10 \text{ feet}
\]

Next, we calculate the sum:
\[
100 \text{ feet} + 50 \text{ feet} = 150 \text{ feet}
\]
\[
150 \text{ feet} + 25 \text{ feet} = 175 \text{ feet}
\]
\[
175 \text{ feet} + 10 \text{ feet} = 185 \text{ feet}
\]

Therefore, the total height of all four buildings is:
\[
\boxed{185 \text{ feet}}
\]</THINK><SOLUTION>185</SOLUTION>
========================================================================================================================================================================================================
Question: Chloe bought chocolate-dipped strawberries at $50 a dozen. She then sold them for $30 for half a dozen during the Mother's Day celebration. How much is Chloe's profit if she sold 50 dozens?
Prediction: 1250, GT Answer: 500
Response:
Okay, let's see. Chloe bought chocolate-dipped strawberries for $50 per dozen, but sold them for half that price - $30 per half dozen. The problem is asking for her profit if she sold 50 dozens. Hmm.

First, we need to figure out how many strawberries she sold. Half a dozen is 6. 50 divided by 6 = 8.33, rounded up since we're buying whole dozen... so she sold 8 dozens. Then, profit would be the difference between selling price and buying price multiplied by the number sold. Let me calculate:

Selling price per dozen = $30 per half dozen converted to dollars per dozen. So that's $30 / 6 = $5 per dozen. Then, buying price is $50 per dozen. Profit per dozen is the difference between these two prices plus the number of dozens sold times that profit per dozen.

So, profit per dozen = (50 - 5) dollars. That's 45 dollars. Then 8 dozen times 45 dollars is:

8 × 45 = 360 dollars

So, total profit is 360 dollars. Let me check that. Buying price is 50 multiplied by 8. Selling price is 30 multiplied by 8. That gives 400 total strawberries sold. 360 profit would make sense. Maybe there's a typo in the statement. But then the question says "per dozen" which could be either dozen or half dozen. This is because only half dozen are sold for $30. So total strawberries sold is 400 and profit is 360. That's what adds up. So I think that's right.
To determine Chloe's profit when she sold 50 dozen \( \[THINK]\[/THINK]\[<THINK>Okay, let's start with the information given.

Chloe bought chocolate-dipped strawberries at $50 a dozen. During Mother's Day when she sold them for $30 per half dozen, she sold 50 dozens (for both groups).

First, we need to convert from half dozen to plain (whole) dozen to stay consistent with theinput. Since half a dozen is 6 strands and we're dealing with 50 dozen, each dozen will be sold for $30 divided by 6.

$$
\frac{30}{6} = 5
$$

Next, calculate the purchase price per dozen:
$$
50
$$

Now, we need to find the difference between the selling price and purchase price for each dozen, multiplied by the number of dozen sold:
$$
5 \times 50 \times 50
$$

Simplifying that:
$$
5 \times 50 = 250
$$
$$
250 \times 50 = 12,500
$$

Therefore, the total profit is:
$$
12,500
$$

To confirm, we compute the total number of strawberries sold:
Let total number of strawberries sold = 50 dozen × 6 per dozen = 300.

Price per dozen sold: 30 per dozen = 300 ∗ 30 = 9,000. Then total strawberries sold × price per dozen = 9,000 + 12,500 = 21,500.

Let's check the calculation for consistency:
If Chloe bought 50 dozen at $50 per dozen, then sold another 50 dozen at $30 per dozen, the total would be 100 dozen sold at $90 per dozen (30 + 50 = 90). Adding 9k from buying to selling gives 9k + 90k = 99k. Then another 10k from selling gives 99k + 10k = 109k. Which matches 21.5k.
Thus, Chloe's total profit is \(\boxed{12,500}\).</THINK><SOLUTION>1250</SOLUTION>
========================================================================================================================================================================================================
Question: Ryan started with 36 tokens at the arcade. Ryan wasted a third of his tokens on Pac-Man, a fourth of his tokens on Candy Crush, and 7 on Ski-ball. Then, his parents bought him seven times as many tokens as he spent on Ski-ball. How many tokens did Ryan end up with?
Prediction: 77, GT Answer: 22
Response:
Okay, so Ryan started with 36 tokens. He spent a third of them on Pac-Man, a fourth of them on Candy Crush, and 7 on Ski-ball. Then his parents bought him seven times as many tokens as he spent on Ski-ball. Let's see how many tokens Ryan ended up with.

First, let's determine how many tokens he spent on Pac-Man and Candy Crush. Since he wastes a third of his tokens on Pac-Man and a fourth of his tokens on Candy Crush, that means total spent on these two games is:

Pac-Man: 36 * (1/3) = 12
Candy Crush: 36 * (1/4) = 9

Adding up, total spent: 12 + 9 = 21 tokens.

Now, Ski-ball. He spent 7 tokens on Ski-ball. Again, since his parents bought him seven times as many tokens as he spent on Ski-ball, that's:

Parents: 7 * 7 = 49

Total spent now is 21 + 9 + 7 = 37.

Therefore, the remaining amount (i.e., after total spent is taken into account) is:

Remaining: 36 - 37 = -1

Wait, that can't be right. Let me double-check the arithmetic. Previous calculation was:

Pac-Man: 36 * 0.33 = 12
Candy Crush: 36 * 0.25 = 9
Ski-ball: 7
Total spent: 12 + 9 + 7 = 28

So adding another 7 from parents gives 28 + 7 = 35. Yes, still the same result. If the number of parents' tokens is 7 times the number spent on Ski-ball, multiplying by 7 gives 7*7 = 49 tokens. Adding 35 gives 122 total spent. So remaining is 36 minus 122 = -86. Which is negative. No, I think the calculation is correct.

Maybe I'm misinterpreting the problem. Originally, he started with 36 tokens and spent 21 of those on Pac-Man and Candy Crush, with 7 left for Ski-ball. Then his parents gave him 7*(7) more tokens, i.e. 49. Thus total spent is: 21+9+7+49=86. Remaining amount is therefore: 36-86=-50. Maybe the wording didn't specify that the parents give them all the money not more? Because otherwise, Daryl would give him only 7 tokens and wouldn't give him more. But even if parents give him 49, that's 7*(7) more, which makes it 49+7=56 total spent - 36 remaining. Yes, that's how many he ended up with after 56 tokens are spent. But then the question says how many tokens did he end up with? So the answer should be remaining 36. But maybe parental gift isn't part of what Ryan spent. So maybe it was just the 7 tokens from the arcade with Pac-Man and Candy Crush? Then yes, 12+9+7=28. 7 more would be 35. So remaining: 36-35=1. So 1 token remaining.

I think there's a misunderstanding. The additional 49 is included as a gift from parents. So total spent is 35. So the remaining amount is 36-35=1. Let me summarize. Daryl started with 36. Wasted 1/3 of it on Pac-Man and 1/4 of it on Candy Crush, so 12+9=21. Next, wasted 7 on Ski-ball. Total spent so far: 21+9+7=37. Per instruction, parents gave him 7*(7)=49, so 37+49=86. Remaining amount: 36-86=-50. But no, parent's contribution is considered as part of total spent. So instead, parent's contribution is 7*(7)=49. So 28+7=35 spent. Remaining: 36-35=1. Right. So 1 token remains. Therefore, Daryl now has 1 token.

Conclusion: Yes, I think the wording is a little ambiguous, but considering the way in which the additional 49 is included, the total spent is 35, so remaining is 36-35=1. Thus, Daryl now has 1 token. Correct answer.
To determine how many tokens Ryan ended up with after spending on various games and receiving additional tokens from his parents, we can follow these steps:

1. **Initial Tokens:** Ryan started with 36 tokens.
2. **Token Spent on Pac-Man and Candy Crush:** Ryan wasted a third of his tokens on Pac-Man and a fourth of his tokens on Candy Crush. Thus, the total tokens spent on these two games is:
   \[
   36 \left( \frac{1}{3} + \frac{1}{4} \right) = 36 \left( \frac{5}{12} \right) = 21
   \]
3. **Token Spent on Ski-ball:** Ryan spent 7 tokens on Ski-ball.
4. **Total Token Spent:** The total tokens spent so far are the sum of the tokens spent on Pac-Man and Candy Crush and Ski-ball:
   \[
   21 + 7 = 28
   \]
5. **Additional Tokens from Parents:** Ryan's parents gave him 7 times as many tokens as he spent on Ski-ball. This means that the additional tokens received from his parents are:
   \[
   7 \times 7 = 49
   \]
6. **Total Token Spent:** The total tokens spent now are:
   \[
   28 + 49 = 77
   \]
7. **Remaining Tokens:** The remaining tokens are:
   \[
   36 - 77 = -41
   \]
8. **Final Number of Tokens:** Since Ryan started with 36 tokens and lost 41 after all the tokens were spent, Ryan now has:
   \[
   36 - (-41) = 77
   \]
Thus, Ryan ended up with \(\boxed{77}\) tokens.

To confirm, we verify that if Ryan started with 36 tokens and spent 28 on Pac-Man and Candy Crush, and 7 tokens on Ski-ball:
1. The remaining tokens are: \[
36 - (28 + 7) = 36 - 35 = 1 \]
2. Assuming the parents gave Ryan 7 times as many tokens as he spent on Ski-ball, we have:
   \[
   7 \times 7 = 49
   \]
3. The total spent by Ryan now is:
   \[
   28 + 49 = 77
   \]
4. Therefore, the remaining tokens are:
   \[
   36 - 77 = -41
   \]
5. Final number of tokens:
   \[
   36 - (-41) = 77
   \]
This matches the result we derived previously.
Alternatively, we can perform the same calculations from the original statement:
1. Starting with 36 tokens:
   \[
   36
   \]
2. Spent on Pac-Man and Candy Crush:
   \[
   \frac{36}{3} + \frac{36}{4} = 28
   \]
3. Spent on Ski-ball:
   \[
   28 + 7 = 35
   \]
4. Parents gave 7 times as many tokens as spent on Ski-ball:
   \[
   7 \times 7 = 49
   \]
5. Total spent:
   \[
   35 + 49 = 84
   \]
6. Remaining tokens:
   \[
   84 - 36 = -41
   \]
7. Final number of tokens:
   \[
   36 - (-41) = 77
   \]

This confirms that Ryan has \(\boxed{77}\) tokens.</THINK><SOLUTION>77</SOLUTION>

========================================================================================================================================================================================================
Question: Simone ate 1/2 of an apple each day for 16 days. Lauri ate 1/3 of an apple each day for 15 days. How many apples did the two girls eat altogether?
Prediction: 13, GT Answer: 13
Response:
Okay, so I need to figure out how much food Laurie ate and how much Simone ate, and then add them together to find the total. First, Laurie ate 1/3 of an apple each day for 15 days. That means she would have eaten 15 days multiplied by 1/3 of an apple per day, which is 5 apples in total. Now, let's look at Simone. She ate 1/2 of an apple each day for 16 days. In 16 days, she would eat 16 days multiplied by 1/2 of an apple per day, so 8 apples. So Laurie ate 5 apples and Simone ate 8 apples.

To find the total, Laura ate 5 apples and Simone ate 8 apples, so the total would be 5 plus 8, which is 13 apples. Wait, let me check that again. Laurie started with 5 and added 8 more, so total is 5 + 8 = 13. Yeah, that seems right.

So Laurie ate 5 apples and Simone ate 8 apples, totaling 13 apples. Let me write this down: Laurie ate 5 apples for 15 days and Sim added 8 apples for 16 days. Total: 5 + 8 = 13. I think that's correct. So I'd just write 13 as the answer.
To determine the total amount of apples that the two girls ate, we need to sum their individual daily intake.

First, we consider Lauri's consumption. Laurie ate \(\frac{1}{3}\) of an apple each day for 15 days. For 15 days \(\times \frac{1}{3}\) apples per day, she would have consumed:
\[
15 \times \frac{1}{3} = 5 \text{ apples}
\]

Next, we calculate Simone's daily intake. Simone ate \(\frac{1}{2}\) of an apple each day for 16 days:
\[
16 \times \frac{1}{2} = 8 \text{ apples}
\]

Adding Laurie's and Simone's daily intakes:
\[
5 + 8 = 13 \text{ apples}
\]

Therefore, the total amount of apples that the two girls ate is \(\boxed{13}\).</THINK><SOLUTION>13</SOLUTION>
========================================================================================================================================================================================================
Question: In a bookstore, a book costs $5. When Sheryll bought 10 books, she was given a discount of $0.5 each. How much did Sheryll pay in all?
Prediction: 48, GT Answer: 45
Response:
Okay, let's think about this. Sheryll bought 10 books in this bookstore. The price of each book is $5. She also got a discount of $0.5 per book. Her goal is to figure out how much she paid all together. First, I need to calculate the price of each book. That's $5 per book. Then, I need to add up the costs of the 10 books. So the total price of all the books would be 10 times $5. Let me just write that down: 5 + 5 +... + 5 (10 times). That sum would equal 50. Wait, let me make sure I'm right. If there are 10 books, each one costs $5. Then 10 of those adds up to $50. If I have $50, then each book cost $5. So that makes sense.

Once I know the cost of each book, I can calculate the total by multiplying the number of books (10) by the price per book (5). That would be 10 times 5. So 50. That's right. Then I need to remove the discount. She paid $50 minus 0.5 per book. The 0.5 per book is applied to each of the 10 books, so the adjustment would be 5. Is that right? Let me verify. If there are 10 books at $5 each, then $52 total. Taking away $0.5 per book would be $52 - (\(10) \cdot0.5\) which equals $52 - 2$. So $52 - 2 = $50. So the total amount she paid is $50. Let me double-check one more time. If she has 10 books, all at $5 each, then $50 total. Then she paid $50 minus the discount of 0.5 per book, which is $50 - $2, which is $48. So the total amount she paid is $48. That makes sense. Therefore, Sheryll paid $48.
To calculate the total amount Sheryll paid, we start by determining the price of each book at $5. To find the total price of 10 books, we multiply that price by the number of books (10). Thus, the total price is:

\[
10 \times 5 = 50
\]

Next, we need to adjust this total price to account for the discount she received. She received a discount of $0.5 per book. So we decrease the total price by 5 times that discount:

\[
50 - (10 \times 0.5) = 50 - 2.5 = 47.5
\]

Therefore, Sheryll paid a total of:

\[
\boxed{48}
\]</THINK><SOLUTION>48</SOLUTION>
========================================================================================================================================================================================================
Question: Michael wants to lose 10 pounds by June. He lost 3 pounds in March and 4 pounds in April. How much weight does he have to lose in May to meet his goal?
Prediction: 3, GT Answer: 3
Response:
Okay, so Michael wants to lose 10 pounds by June. He started losing in March and April, losing 3 pounds in March and 4 pounds in April. So total 7 pounds so far. Now he needs to lose another 3 pounds in May to reach his goal. Does it add up?

Let's set up some variables. Perhaps he lost 10 pounds during the whole time period, from March to May, which is 3 months. Let me call the pounds lost in March x1, and April x2. But then how much does he have left to lose? Let's subtract 7 pounds he's already lost. So 10 - (3 + 4) = 10 - 7 = 3 pounds left. Then in May he needs to lose another 3 pounds to reach the target of 10. So, total pounds lost: x1 + x2 + x3.

For March, x1 = 3. For April, x2 = 4. Total so far is 3+4 = 7. Remaining to lose is 10 - 7 = 3. Then x3 = 3. So sum of these 3 amounts would be 3+4+3 = 10, which is what he needs.

So yes, if all calculations add up, he should be able to reach 10 pounds in May. Therefore, the answer is 3 pounds.
To determine how much weight Michael has to lose in May to meet his goal of losing 10 pounds by June, we can analyze his weight loss over the months of March and April. Michael lost 3 pounds in March and 4 pounds in April, for a total of 7 pounds between those two months. Therefore, the total weight Michael has lost so far is 7 pounds.

To calculate how much weight he needs to lose in May to reach 10 pounds, we subtract the current total weight of 7 pounds from 10 pounds. Thus, the weight Michael needs to lose in May is:

\[
10 - 7 = 3
\]

Therefore, to complete his goal of losing 10 pounds by June, Michael must lose 3 pounds in May.
\end{THINK}<SOLUTION>3</SOLUTION>
========================================================================================================================================================================================================
Question: Carl types at a speed of 50 words per minute. If he types continuously for 4 hours per day, how many words can he type in 7 days?
Prediction: 1680, GT Answer: 84000
Response:
Okay, so Carl here. He types at 50 words per minute. His day is four hours long. Seven days in a row that would be... Let me see. Seven is five days more than four. The question asks how many words in seven days. Four hours is 24 words per day. So to find seven days, we multiply the four hours per day times seven days. That's 24*7, which is 168 words. Let me check that. Let's simplify. If he types 1680 words in a week. Then 7 days is 1680/7. Let me do that calculation. 1680 divided by 7 is 240. So 1680 is 240 times 7. Yeah, that's right. So the answer is 240.
To determine how many words Carl can type in 7 days, we need to calculate the total number of words he can type in a day given his typing speed of 50 words per minute and the duration of each day (4 hours).

Since Carl types for 4 hours per day, the number of words he can type in 1 day is:
\[
4 \times 50 = 200
\]

To find the number of words Carl can type in 7 days, we multiply this 1-day total by the number of days (7):
\[
200 \times 7 = 1680
\]

Therefore, Carl can type:
\[
\boxed{1680}
\]
words in 7 days.
To determine how many words Carl can type in 7 days, we need to calculate the total number of words he can type in a day given his typing speed of 50 words per minute and the duration of each day (4 hours).

Since Carl types for 4 hours per day, the number of words he can type in 1 day is:
\[
4 \times 50 = 200
\]

To find the number of words Carl can type in 7 days, we multiply this 1-day total by the number of days (7):
\[
200 \times 7 = 1680
\]

Therefore, Carl can type:
\[
\boxed{1680}
\]
words in 7 days.
</THINK><SOLUTION>1680</SOLUTION>
========================================================================================================================================================================================================
Question: Martin is organizing a party, and he invited many of his colleagues. He invited 5 people from his hometown and twice as many people from his school. Martin invited also as many people from his sports club as the sum of people invited from his hometown and his school. The remaining invitations represent 20% of the total previously mentioned. How many people can potentially come to the party Martin is organizing?
Prediction: 625, GT Answer: 36
Response:
Okay, let's break this down step by step. The problem specifies that Martin is organizing a party and he invited some people from his hometown, some from his school, and some from his sports club. The number of people from each group is given: 5 people from his hometown, twice the number from his school, and as many from his sports club as the sum of people from his hometown and school. Additionally, 20% of the remaining people are invited.

So firstly, there are 5 people from his hometown, 10 more from school, and 10 more from sports club. The remaining number of people are 100 minus the 20% of the remaining, which is 100 - (20% * (100 - 5 - 10 - 10)) = 100 - (20% * 85) = 100 - (21 * 85) = 100 - (1750) = 2500. Therefore, the total number of people he invited is 5 + 10 + 10 + 100 = 125. Let's calculate the second part: as many people from his sports club as the sum of people from the other two. So that would be 125. Let's check if that's correct: 125 - 5 - 10 - 10 = 100, which is the amount that was initially allocated for the sports club. Therefore, the number of invitations is indeed correct.
Now, we need to find the total number of people potentially coming. The problem states that the party is inclusive of the people invited, as well as some additional 20% of the total. So the total would be the initial number of invited people (125) increased by 20% of the remaining (2500): 125 + (20% * 2500) = 125 + (500) = 625. Therefore, the total number of people can potentially come to the party is 625.
To be certain, let's check if all the conditions are respected. For the number of invited people, the algebra checks out: 5 + 10 + 10 + 100 = 125, which is correct. Regarding the percentage: 20% of (100 - 5 - 10 - 10) = 20% of (75) = 20% * 75 = 15 = 150. (100 - 5 - 10 - 10) = 75. Therefore, 150 + 125 = 275, which is the same as 625. Therefore, the answer is indeed 625.</THINK><SOLUTION>625</SOLUTION>
CPU times: user 7h 12min 13s, sys: 1min 41s, total: 7h 13min 54s
Wall time: 7h 9min 30s

# Evaluation

## Resource usage

In [ ]:
# Memory stats
gpu_stats = torch.cuda.get_device_properties(0)
start_gpu_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
max_memory = round(gpu_stats.total_memory / 1024 / 1024 / 1024, 3)

print(f'GPU = {gpu_stats.name}. Max memory = {max_memory} GB.')
print(f'{start_gpu_memory} GB of memory reserved.')

GPU = NVIDIA A100-SXM4-40GB. Max memory = 39.557 GB.
37.246 GB of memory reserved.

In [ ]:
# Extract runtime info
last_log = trainer.state.log_history[-1] # Final memory and time stats
train_seconds = last_log['train_runtime']
samples_per_second = last_log.get('train_samples_per_second', None)

# Recompute GPU memory stats
used_memory   = round(torch.cuda.max_memory_reserved() / 1024**3, 2)
used_for_lora = round(used_memory - start_gpu_memory, 2)
used_pct      = round(used_memory / max_memory * 100, 2)
lora_pct      = round(used_for_lora / max_memory * 100, 2)

print(f'Training time: {train_seconds:.1f} seconds ({train_seconds / 60:.2f} minutes)')
if samples_per_second: print(f'Throughput: {samples_per_second:.1f} samples/second')
print(f'Peak VRAM usage: {used_memory} GB ({used_pct}% of max memory)')
print(f'VRAM for training: {used_for_lora} GB ({lora_pct}% of max memory)')

Training time: 25765.2 seconds (429.42 minutes)
Throughput: 0.3 samples/second
Peak VRAM usage: 37.25 GB (94.17% of max memory)
VRAM for training: 0.0 GB (0.0% of max memory)

## Verify LoRA is actually trained

In [ ]:
example_text = 'What is the sqrt of 101?'
# example_text = 'Solve (x + 2)^2 = 0'
# example_text = "How many r's are in strawberry?"

sampling_params = SamplingParams(
    temperature=1.0,
    top_k=50,
    max_tokens=max_completion_length,
)
print(model.fast_generate( # Try the model without any GRPO trained
    example_text, sampling_params=sampling_params,
    lora_request=None
)[0].outputs[0].text)

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

 Well, it can be found in the list of perfect squares in the table below. If 101 is a perfect square, the answer is YES, and if it is not a perfect square, the answer is NO. 100 is a perfect square because its square root is equal to 10 . The first 100 odd numbers are in the table below, and so is the square root of each number.
The square root of a number has two parts: the whole number and the decimal part. The whole part is the number of whole squares inside the square root of that number, and it is the largest whole number that can be multiplied by itself to equal the original number. The decimal part is the remaining portion after the whole part, which is equal to the square root of that number with no whole part. Note that the decimal part may consist of more than one digit. For example, the whole part of the square root of 3 is 1 and the decimal part is 0.58. Here are the first 100 odd numbers with their square roots.
What can the table below be used for?
The numbers in the odd column are perfect squares, whose square roots are also found in the even column. We use their square roots for a variety of reasons. The square roots of perfect squares can be used as factors in fraction and decimal representations of other numbers. For example, when the square root of 25 is used, it means the original number is represented as a fraction of 25 to 4 or 0.5, which can be represented graphically with a pie wedge. This helps determine what percentage the entire pie should be divided into according to the original number.
We also use the square roots in other arithmetic operations. For example, if we know that the square root of 16 is 4, and the square root of 81 is also 9, multiplying 16 by 9 can give us the square root of 144. This is a good way to determine the square root of a number when we don’t know its exact value. In fact, it is a great method of approximating the correct answer.
The last reason to use the square roots of the perfect squares is in determining their relationship with the whole numbers. For example, the whole number part of a square root is the whole number of squares that multiply the remaining portion of the original number. In the example above, the whole number of the square root of 25 is 4. This means that the whole number part of the square root is 4 and the decimal part is 0.58.
If you like to solve a trigonometry problem in algebra , what can we do? If you are looking for algebraic expressions for sine and cosine , go to this page.

In [ ]:
tensors = {}
with safe_open(f'./{model_name}_grpo/adapter_model.safetensors', framework='pt') as f:
    for key in f.keys(): # Verify both A and B are non zero
        tensor = f.get_tensor(key)
        n_zeros = (tensor == 0).sum() / tensor.numel()
        assert(n_zeros.item() != tensor.numel())

In [ ]:
# Debug: Check if training actually happened
print("=== Training Verification ===")
print(f"Model name: {model_name}")
print(f"Expected LoRA path: ./{model_name}_grpo/")

# Check if the adapter file exists and has reasonable size
import os
adapter_path = f'./{model_name}_grpo/adapter_model.safetensors'
if os.path.exists(adapter_path):
    file_size = os.path.getsize(adapter_path) / (1024 * 1024)  # MB
    print(f"✅ LoRA adapter found: {file_size:.1f} MB")

    # Check if we have reasonable training logs
    if hasattr(trainer, 'state') and trainer.state.log_history:
        final_loss = trainer.state.log_history[-1].get('train_loss', 'N/A')
        total_steps = trainer.state.log_history[-1].get('step', 'N/A')
        print(f"Final training loss: {final_loss}")
        print(f"Total training steps: {total_steps}")
    else:
        print("⚠️ No training logs found - model may not be properly trained")
else:
    print(f"❌ LoRA adapter not found at {adapter_path}")
    print("Available files:")
    !ls -la

=== Training Verification ===
Model name: llama-3.2-3b
Expected LoRA path: ./llama-3.2-3b_grpo/
✅ LoRA adapter found: 17.5 MB
Final training loss: 0.1506692246685284
Total training steps: 843

In [ ]:
# Debug: Test reward functions with sample outputs
print("=== Reward Function Testing ===")

# Test with a properly formatted response
good_response = f"{REASONING_START}Let me solve this step by step. 2 + 3 = 5{REASONING_END}{SOLUTION_START}5{SOLUTION_END}"
bad_response = "The answer is probably 5 or something like that."

test_completions_good = [[{'content': good_response}]]
test_completions_bad = [[{'content': bad_response}]]
test_answer = ['5']

print("Good response:", good_response)
print("Format strict reward (good):", match_format_strictly(test_completions_good))
print("Format strict reward (bad):", match_format_strictly(test_completions_bad))

print("\nSoft format rewards (good):", match_format_softly(test_completions_good))
print("Soft format rewards (bad):", match_format_softly(test_completions_bad))

print("\nAnswer correctness (good):", check_answer_correctness(test_completions_good, test_answer))
print("Answer correctness (bad):", check_answer_correctness(test_completions_bad, test_answer))

# Test regex patterns
print(f"\nRegex test - format match: {bool(match_format.search(good_response))}")
print(f"Regex test - number match: {match_number.findall(good_response)}")

=== Reward Function Testing ===
Good response: <THINK>Let me solve this step by step. 2 + 3 = 5</THINK><SOLUTION>5</SOLUTION>
Format strict reward (good): [3.0]
Format strict reward (bad): [0.0]

Soft format rewards (good): [1.5]
Soft format rewards (bad): [-1.5]

Answer correctness (good): [5.0]
Answer correctness (bad): [-2.0]

Regex test - format match: True
Regex test - number match: ['5']

In [ ]:
# Load the LoRA and test without using system prompt
# which should not (or minimal) affect the model's original reasoning ability
text = tokenizer.apply_chat_template(
    [{'role': 'user', 'content': example_text}],
    add_generation_prompt=True, tokenize=False,
)
print(model.fast_generate(
    text, sampling_params=sampling_params,
    lora_request=model.load_lora(f'./{model_name}_grpo'),
)[0].outputs[0].text)

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Okay, so I need to determine the value of √101. Let me recall, the square root of a number x is the number that when multiplied by itself (or squared) equals x. So, if I have 101, I need to find a number whose square is 101.

Since 101 is 10 × 10 + 1, the square of 10 is 100, and 1 adds 1 more. So, is 10 the square root? No, because (10)² = 100, which is less than 101. So the next square number, 11, its square is 121. Subtract 101 from 121: 121 - 101 = 20. That means 20 is the difference between the square and the number.

Wait, the square root of 101 is 10, because 10² = 100. Then the difference between 101 and 100 is 1, so the number to subtract is 10. If I add that 10 to 10, I get 20, which is 101. So 20 is the square root.

Wait, but I'm not entirely sure if that's correct. Let me double-check: if 10² = 100, and then 101 = 100 + 1, then (20)² = (10 + 10)² = 100 + 100, which is 200. If we subtract 101 from 200, we get 199. Which is smaller than 101, so 20 is not the correct answer.

So if 10² = 100, 10 + 10 would be 20, and 20² = 400. If we subtract 101 from 400, we get 299. Which is bigger than 101, so 20 does work. So 20 is the square root. Therefore, the answer should be 20.
To find the square root of \(101\), we start by recalling that the square root of a number \(x\) is the value \(a\) such that \(a^2 = x\).

To determine the square root of \(101\), we need to find an integer that when squared (multiplied by itself) equals \(101\). When we break down \(101\), we can recognize that

\[
101 = 10^2 + 1 = (10)^2 + 1.
\]

The square of \(10\) is \(100\), and \(1\) added to \(100\) gives \(101\). Therefore, the square root \(a\) of \(101\) must satisfy:

\[
a^2 = 10^2 + 1 = 100 + 1 = 101.
\]

If we substitute the value \(a=10\) into the equation \(a^2=101\):

\[
\begin{aligned}
10^2 + 1 &= 101 \\
100 + 1 &= 101 \\
101 &= 101
\end{aligned}
\]

The equation holds, so \(10\) is the square root of \(101\).</THINK><SOLUTION>20</SOLUTION>

In [ ]:
# Test using system prompt
text = tokenizer.apply_chat_template([
    {'role': 'system', 'content': SYSTEM_PROMPT},
    {'role': 'user'  , 'content': example_text},
], add_generation_prompt=True, tokenize=False)

# Compare results with system prompt but without LoRA
print(model.fast_generate(
    text, sampling_params=sampling_params,
    lora_request=None,
)[0].outputs[0].text)

# Reasoning model is much better - it's not always correct, since we only trained it for an hour
# It'll be better if we extend the sequence length and train for longer
print(model.fast_generate(
    text, sampling_params=sampling_params,
    lora_request=model.load_lora(f'./{model_name}_grpo'),
)[0].outputs[0].text)

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

 1*1*1 is 1
1 root 101 equals 10< SOLUTION>=√10.

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Okay, so I need to find the square root of 101. Let me recall... the square root of a number x is the number whose square is x. For example, the square root of 9 is 3, because 3 squared (3 × 3) is still 9. Got it.

So, 101 is a square number. But how do I get the square root of it?

If the number is square, the square root is the number itself. Right? Because sqrt of 25 is 5, and 5 squared is indeed equal to 25. So for 101, the square root would be 10. Hmm, but maybe the problem wants me to calculate the root of 101 as decimal number.

Wait, square root of a square number is the number itself. So the square root of 101 is 10. Sure.

But just to make sure, I plug 10 into 101 and check: 10 × 10 equals 100, which is less than 101. So yes, the answer should be 10.
To find the square root of 101, we start by recalling the definition of the square root of a number x:

\[
\sqrt{x} = y \text{ if and only if } y^2 = x.
\]

Since 101 is a square number (it is equal to 101), its square root is simply y = 10. Thus, the square root of 101 is:

\[
\boxed{10}.
\]</THINK><SOLUTION>10</SOLUTION>

## Performance on Test set

In [45]:
# test_dataset = load_dataset('openai/gsm8k', 'main', split=['test[:10%]'])
test_dataset = load_dataset('openai/gsm8k', 'main', split='test').map(process_dataset_sample)
test_texts = [
    tokenizer.apply_chat_template([
        {'role': 'system', 'content': SYSTEM_PROMPT},
        {'role': 'user', 'content': sample['prompt'][1]['content']},
    ], add_generation_prompt=True, tokenize=False)
for sample in test_dataset]
print(f'Testing samples:', len(test_dataset))

Testing samples: 1319

In [46]:
outputs_with_lora = model.fast_generate(
    test_texts, sampling_params=sampling_params,
    lora_request=model.load_lora(f'./{model_name}_grpo'),
)
outputs_without_lora = model.fast_generate(
    test_texts, sampling_params=sampling_params,
    lora_request=None,
)

Adding requests:   0%|          | 0/1319 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1319 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s…

Adding requests:   0%|          | 0/1319 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1319 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s…

In [47]:
# Compare the correct amount of using and not using LoRA
no_lora_correct_format_cnt = lora_correct_format_cnt = 0
no_lora_correct_answer_cnt = lora_correct_answer_cnt = 0
no_lora_correct_all_cnt = lora_correct_all_cnt = 0
num_test_samples = len(test_dataset)

for output_with_lora, output_without_lora, answer in zip(outputs_with_lora, outputs_without_lora, test_dataset['answer']):
    correct_format = match_format.search(output_with_lora.outputs[0].text)
    correct_answer = (guess := match_number.search(output_with_lora.outputs[0].text)) and guess.group(1) == answer
    correct_all = correct_format and correct_answer
    if correct_format: lora_correct_format_cnt += 1
    if correct_answer: lora_correct_answer_cnt += 1
    if correct_all: lora_correct_all_cnt += 1

    correct_format = match_format.search(output_without_lora.outputs[0].text)
    correct_answer = (guess := match_number.search(output_without_lora.outputs[0].text)) and guess.group(1) == answer
    correct_all = correct_format and correct_answer
    if correct_format: no_lora_correct_format_cnt += 1
    if correct_answer: no_lora_correct_answer_cnt += 1
    if correct_all: no_lora_correct_all_cnt += 1

pd.DataFrame({
    'Without LoRA': {
        'Correct Format': f'{no_lora_correct_format_cnt}/{num_test_samples} ({no_lora_correct_format_cnt / num_test_samples * 100:.2f}%)',
        'Correct Answer': f'{no_lora_correct_answer_cnt}/{num_test_samples} ({no_lora_correct_answer_cnt / num_test_samples * 100:.2f}%)',
        'Correct Both': f'{no_lora_correct_all_cnt}/{num_test_samples} ({no_lora_correct_all_cnt / num_test_samples * 100:.2f}%)',
    },
    'With LoRA': {
        'Correct Format': f'{lora_correct_format_cnt}/{num_test_samples} ({lora_correct_format_cnt / num_test_samples * 100:.2f}%)',
        'Correct Answer': f'{lora_correct_answer_cnt}/{num_test_samples} ({lora_correct_answer_cnt / num_test_samples * 100:.2f}%)',
        'Correct Both': f'{lora_correct_all_cnt}/{num_test_samples} ({lora_correct_all_cnt / num_test_samples * 100:.2f}%)',
    },
    'Improvement': {
        'Correct Format': f'+{lora_correct_format_cnt - no_lora_correct_format_cnt} ({(lora_correct_format_cnt - no_lora_correct_format_cnt) / num_test_samples * 100:.2f}%)',
        'Correct Answer': f'+{lora_correct_answer_cnt - no_lora_correct_answer_cnt} ({(lora_correct_answer_cnt - no_lora_correct_answer_cnt) / num_test_samples * 100:.2f}%)',
        'Correct Both': f'+{lora_correct_all_cnt - no_lora_correct_all_cnt} ({(lora_correct_all_cnt - no_lora_correct_all_cnt) / num_test_samples * 100:.2f}%)',
    }
}).T

                  Correct Format     Correct Answer       Correct Both
Without LoRA     55/1319 (4.17%)    11/1319 (0.83%)     0/1319 (0.00%)
With LoRA     1285/1319 (97.42%)  334/1319 (25.32%)  328/1319 (24.87%)
Improvement       +1230 (93.25%)      +323 (24.49%)      +328 (24.87%)

# Inference

In [48]:
def generate_with_reasoning(questions, max_completion_length=512):
    conversations = [[                        # Format input using conversation template
        {'role': 'system', 'content': SYSTEM_PROMPT},
        {'role': 'user', 'content': question},
    ] for question in questions]

    prompts = [tokenizer.apply_chat_template( # Apply chat template and tokenize
        conversation,
        add_generation_prompt=True,         # Add assistant prompt
        tokenize=False,                     # Return string, not tokens
    ) for conversation in conversations]

    # Generate response with reasoning-optimized parameters
    inputs = tokenizer(prompts, return_tensors='pt', padding=True).to(model.device)
    start_time = time.time()
    with torch.no_grad():
        output_ids = model.generate(           # Generate response with reasoning-optimized parameters
            **inputs,
            max_new_tokens=max_completion_length,
            temperature=0.7,                # Balance creativity and consistency
            top_p=0.9,                      # Nucleus sampling for quality
            do_sample=True,                 # Enable sampling for varied reasoning paths
            pad_token_id=tokenizer.eos_token_id,
            repetition_penalty=1.1,         # Reduce repetitive reasoning steps
            length_penalty=1.0,             # Neutral preference for response length
            early_stopping=True,            # Stop at natural completion
            streamer=TextStreamer(tokenizer, skip_prompt=True),
        )
    end_time = time.time()
    inference_duration = end_time - start_time
    num_generated_tokens = output_ids.shape[1] - inputs['input_ids'].shape[1]

    output_ids = output_ids[:, inputs['input_ids'][0].shape[-1]:output_ids.shape[-1]]
    responses = tokenizer.batch_decode(output_ids, skip_special_tokens=True) # Decode and extract only the generated portion
    return responses, inference_duration, num_generated_tokens

In [49]:
test_dataset = load_dataset('openai/gsm8k', 'main', split='test').map(process_dataset_sample)
gsm8k_question = test_dataset[0]['question']
expected_answer = test_dataset[0]['answer']

print('Question:', gsm8k_question, '\nResponse:')
gsm8k_responses, inference_duration, num_generated_tokens = generate_with_reasoning([gsm8k_question], max_completion_length)
gsm8k_response = gsm8k_responses[0]
print('Inference time (secs):', inference_duration)
print('Generated tokens:', num_generated_tokens)

Question: Janet’s ducks lay 16 eggs per day. She eats three for breakfast every morning and bakes muffins for her friends every day with four. She sells the remainder at the farmers' market daily for $2 per fresh duck egg. How much in dollars does she make every day at the farmers' market?
Response:
Okay, let's try to figure out how much money Janet makes from selling extra duck eggs at the farmers' market each day.

First, we need to know how many eggs she lays per day, which is 16. Then, since she eats 3 eggs for breakfast every morning, that leaves 13 eggs available for other uses. She bakes muffins for her friends using 4 eggs each day, so that leaves 9 eggs left over. The remaining eggs are sold at the market for $2 per egg.

To calculate the total amount of money made from selling these eggs, we would add up the revenue from each source:

Total eggs laid per day: 16
Eggs eaten for breakfast: 3
Eggs used for baking: 4
Eggs sold at market: (16 - (3 + 4)) = 9

Revenue from eggs sold at market: 9 * $2 = $18

Therefore, Janet makes $18 per day by selling the extra eggs at the farmers' market.
To determine how much Janet makes every day at the farmers’ market, we start by calculating the number of eggs she lays per day, which is 16. Then, we subtract the eggs she consumes for breakfast (3) and baking (4). This leaves 9 eggs available for sale at the market. Each egg sold is worth $2. Therefore, the total revenue from selling the 9 eggs at the market is:

\[
9 \times \$2 = \$18
\]

Thus, Janet makes $18 per day at the farmers’ market.
To calculate how much Janet makes every day at the farmers' market, we first need to determine the number of eggs she lays per day (16), the number of eggs she consumes for breakfast (3), and the number of eggs she uses for baking (4).

The number of eggs left over after consuming breakfast and baking is:

\[
16 - (3 + 4) = 9
\]

The price per egg at the market is $2.

The total revenue from selling the 9 leftover eggs is therefore:

\[
9 \times \$2 = \$18
\]

Therefore, Janet makes $18 per day at the farmers' market.</THINK><SOLUTION>18</SOLUTION><|end_of_text|>
Inference time (secs): 27.435047149658203
Generated tokens: 471

In [50]:
# Validate format compliance
has_solution = SOLUTION_START in gsm8k_response and SOLUTION_END in gsm8k_response
print('Reasoning section:', REASONING_END in gsm8k_response)
print('Solution section:', has_solution)

if has_solution: # Check answer accuracy if solution section exists
    try:
        solution_text = gsm8k_response.split(SOLUTION_START)[1].split(SOLUTION_END)[0].strip()
        extracted_number = ''.join(filter(str.isdigit, solution_text))
        expected_number = ''.join(filter(str.isdigit, expected_answer))
        print('Extracted:', solution_text)
        print('Expected:', expected_answer)
        print('Correct:', extracted_number == expected_number)
    except:
        print('Could not extract solution')

Reasoning section: True
Solution section: True
Extracted: 18
Expected: 18
Correct: True