# Environment Setup

In [ ]:
!uv pip install bitsandbytes xformers triton unsloth vllm==0.10.2
!uv pip install transformers==4.55.4
!uv pip install --no-deps trl==0.22.2

Using Python 3.12.12 environment at: /usr
Audited 5 packages in 112ms
Using Python 3.12.12 environment at: /usr
Audited 1 package in 95ms
Using Python 3.12.12 environment at: /usr
Audited 1 package in 108ms

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [ ]:
%cd '/content/drive/MyDrive/multi-reward-math-reasoning/Llama'

/content/drive/MyDrive/multi-reward-math-reasoning/Llama

In [ ]:
%ls

'Llama-3.2-1b outputs'/  'Llama-3.2-3b outputs'/
 Llama-3.2-3B.ipynb       Llama.ipynb

In [ ]:
from unsloth import FastLanguageModel
from trl import SFTConfig, GRPOConfig, SFTTrainer, GRPOTrainer
from vllm import SamplingParams

import gc
import re
import time
import torch
import numpy as np
import pandas as pd

from pathlib import Path
from tqdm.notebook import tqdm
from datasets import load_dataset, Dataset
from safetensors import safe_open

from peft import LoraConfig, get_peft_model, TaskType
from transformers import (
    AutoTokenizer, AutoModelForCausalLM,
    BitsAndBytesConfig, TextStreamer
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
INFO 10-21 23:14:25 [__init__.py:216] Automatically detected platform cuda.
🦥 Unsloth Zoo will now patch everything to make training faster!

# Model Setup

In [ ]:
model_id = 'unsloth/Llama-3.2-1B'          # Select model optimized for instruction-following and reasoning
model_name = model_id.split('/')[-1].lower()  # Extract model name from ID
max_seq_length = 2048                         # Can increase for longer reasoning traces
lora_rank = 32                                # Larger rank = smarter, but slower

In [ ]:
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=model_id,
    max_seq_length=max_seq_length,
    load_in_4bit=False,         # False for LoRA 16bit
    fast_inference=True,        # Enable vLLM fast inference
    max_lora_rank=lora_rank,
    gpu_memory_utilization=0.9, # Reduce if out of memory
)
model = FastLanguageModel.get_peft_model(
    model,
    r=lora_rank,                          # Rank: adaptation capacity (16 good for reasoning tasks)
    lora_alpha=lora_rank * 2,             # Scaling factor (typically 2x rank)
    lora_dropout=0.1,                     # Regularization to prevent overfitting
    target_modules=[                      # Remove QKVO if out of memory
        'q_proj', 'k_proj', 'v_proj', 'o_proj',
        'gate_proj', 'up_proj', 'down_proj',
    ],
    use_gradient_checkpointing='unsloth', # Reduces memory usage
    random_state=3407,
)

INFO 10-21 23:14:34 [vllm_utils.py:694] Unsloth: Patching vLLM v1 graph capture
INFO 10-21 23:14:34 [vllm_utils.py:722] Unsloth: Patching vLLM v0 graph capture
==((====))==  Unsloth 2025.10.7: Fast Llama patching. Transformers: 4.55.4. vLLM: 0.10.2.
   \\   /|    NVIDIA A100-SXM4-40GB. Num GPUs = 1. Max memory: 39.557 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.8.0+cu126. CUDA: 8.0. CUDA Toolkit: 12.6. Triton: 3.4.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.32.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: vLLM loading unsloth/Llama-3.2-1B with actual GPU utilization = 88.97%
Unsloth: Your GPU has CUDA compute capability 8.0 with VRAM = 39.56 GB.
Unsloth: Using conservativeness = 1.0. Chunked prefill tokens = 2048. Num Sequences = 320.
Unsloth: vLLM's KV Cache can use up to 32.85 GB. Also swap space = 6 GB.
WARNING 10-21 23:14:43 [compilation.py:456] full_cuda_graph is deprecated, use cudagraph_mode=FULL instead.
Unsloth: Not an error, but `device` is not supported in vLLM. Skipping.
INFO 10-21 23:14:43 [utils.py:328] non-default args: {'dtype': torch.bfloat16, 'seed': 0, 'max_model_len': 2048, 'enable_prefix_caching': True, 'swap_space': 6, 'gpu_memory_utilization': 0.88969201168322, 'max_num_batched_tokens': 2048, 'max_num_seqs': 320, 'max_logprobs': 0, 'disable_log_stats': True, 'enable_lora': True, 'max_lora_rank': 32, 'enable_chunked_prefill': True, 'compilation_config': {"level":3,"debug_dump_path":"","cache_dir":"","backend":"inductor","custom_ops":[],"splitting_ops":null,"use_inductor":true,"compile_sizes":null,"inductor_compile_config":{"epilogue_fusion":true,"max_autotune":false,"shape_padding":true,"trace.enabled":false,"triton.cudagraphs":true,"debug":false,"dce":true,"memory_planning":true,"coordinate_descent_tuning":false,"trace.graph_diagram":false,"compile_threads":12,"group_fusion":true,"disable_progress":false,"verbose_progress":true,"triton.multi_kernel":0,"triton.use_block_ptr":true,"triton.enable_persistent_tma_matmul":true,"triton.autotune_at_compile_time":false,"triton.cooperative_reductions":false,"cuda.compile_opt_level":"-O2","cuda.enable_cuda_lto":true,"combo_kernels":false,"benchmark_combo_kernel":true,"combo_kernel_foreach_dynamic_shapes":true,"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":2,"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":null,"cudagraph_copy_inputs":false,"full_cuda_graph":true,"pass_config":{},"max_capture_size":null,"local_cache_dir":null}, 'model': 'unsloth/Llama-3.2-1B'}
INFO 10-21 23:14:58 [__init__.py:742] Resolved architecture: LlamaForCausalLM
INFO 10-21 23:14:58 [__init__.py:1815] Using max model len 2048
INFO 10-21 23:15:00 [scheduler.py:222] Chunked prefill is enabled with max_num_batched_tokens=2048.
WARNING 10-21 23:15:00 [lora.py:92] `lora_extra_vocab_size` is deprecated and will be removed in v0.12.0. Additional vocabulary support for LoRA adapters is being phased out.
INFO 10-21 23:15:01 [core.py:76] Initializing a V1 LLM engine (v0.10.2) with config: model='unsloth/Llama-3.2-1B', speculative_config=None, tokenizer='unsloth/Llama-3.2-1B', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=2048, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=unsloth/Llama-3.2-1B, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"inductor","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2","vllm.mamba_mixer","vllm.short_conv","vllm.linear_attention","vllm.plamo2_mamba_mixer","vllm.gdn_attention"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"epilogue_fusion":true,"max_autotune":false,"shape_padding":true,"trace.enabled":false,"triton.cudagraphs":true,"debug":false,"dce":true,"memory_planning":true,"coordinate_descent_tuning":false,"trace.graph_diagram":false,"compile_threads":12,"group_fusion":true,"disable_progress":false,"verbose_progress":true,"triton.multi_kernel":0,"triton.use_block_ptr":true,"triton.enable_persistent_tma_matmul":true,"triton.autotune_at_compile_time":false,"triton.cooperative_reductions":false,"cuda.compile_opt_level":"-O2","cuda.enable_cuda_lto":true,"combo_kernels":false,"benchmark_combo_kernel":true,"combo_kernel_foreach_dynamic_shapes":true,"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":2,"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":true,"pass_config":{},"max_capture_size":512,"local_cache_dir":null}
INFO 10-21 23:15:02 [parallel_state.py:1165] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 10-21 23:15:02 [topk_topp_sampler.py:69] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
INFO 10-21 23:15:02 [gpu_model_runner.py:2338] Starting to load model unsloth/Llama-3.2-1B...
INFO 10-21 23:15:03 [gpu_model_runner.py:2370] Loading model from scratch...
INFO 10-21 23:15:03 [cuda.py:362] Using Flash Attention backend on V1 engine.
INFO 10-21 23:15:03 [weight_utils.py:348] Using model weights format ['*.safetensors']
INFO 10-21 23:15:04 [weight_utils.py:406] No model.safetensors.index.json found in remote.

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]

INFO 10-21 23:15:05 [default_loader.py:268] Loading weights took 0.73 seconds
INFO 10-21 23:15:05 [punica_selector.py:19] Using PunicaWrapperGPU.
INFO 10-21 23:15:06 [gpu_model_runner.py:2392] Model loading took 2.3782 GiB and 1.934611 seconds
INFO 10-21 23:15:12 [backends.py:539] Using cache directory: /root/.cache/vllm/torch_compile_cache/5df3daed28/rank_0_0/backbone for vLLM's torch.compile
INFO 10-21 23:15:12 [backends.py:550] Dynamo bytecode transform time: 6.09 s
INFO 10-21 23:15:15 [backends.py:161] Directly load the compiled graph(s) for dynamic shape from the cache, took 1.705 s
INFO 10-21 23:15:16 [monitor.py:34] torch.compile takes 6.09 s in total
INFO 10-21 23:15:18 [gpu_worker.py:298] Available KV cache memory: 31.32 GiB
INFO 10-21 23:15:18 [kv_cache_utils.py:864] GPU KV cache size: 1,026,400 tokens
INFO 10-21 23:15:18 [kv_cache_utils.py:868] Maximum concurrency for 2,048 tokens per request: 501.17x
INFO 10-21 23:15:18 [vllm_utils.py:699] Unsloth: Running patched vLLM v1 `capture_model`.
WARNING 10-21 23:15:18 [gpu_model_runner.py:3258] CUDAGraphMode.FULL is not supported with FlashAttentionMetadataBuilder backend (support: AttentionCGSupport.UNIFORM_BATCH); setting cudagraph_mode=FULL_AND_PIECEWISE

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 67/67 [00:04<00:00, 13.42it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 43/43 [00:03<00:00, 13.20it/s]

INFO 10-21 23:15:26 [gpu_model_runner.py:3118] Graph capturing finished in 8 secs, took 0.61 GiB
INFO 10-21 23:15:26 [vllm_utils.py:706] Unsloth: Patched vLLM v1 graph capture finished in 8 secs.

INFO 10-21 23:15:28 [gpu_worker.py:391] Free memory on device (39.03/39.56 GiB) on startup. Desired GPU memory utilization is (0.88969201168322, 35.19 GiB). Actual usage is 2.38 GiB for weight, 1.47 GiB for peak activation, 0.02 GiB for non-torch memory, and 0.61 GiB for CUDAGraph memory. Replace gpu_memory_utilization config with `--kv-cache-memory=32817368166` to fit into requested memory, or `--kv-cache-memory=36936476160` to fully utilize gpu memory. Current kv cache memory in use is 33633160294 bytes.
INFO 10-21 23:15:28 [core.py:218] init engine (profile, create kv cache, warmup model) took 22.07 seconds
INFO 10-21 23:15:29 [llm.py:295] Supported_tasks: ('generate',)
INFO 10-21 23:15:29 [__init__.py:36] No IOProcessor plugins requested by the model
Unsloth: Just some info: will skip parsing ['q_norm', 'norm2', 'input_layernorm', 'layer_norm2', 'post_attention_layernorm', 'layer_norm1', 'norm1', 'pre_feedforward_layernorm', 'post_feedforward_layernorm', 'post_layernorm', 'k_norm', 'ffn_norm', 'attention_norm']
Unsloth: Just some info: will skip parsing ['q_norm', 'norm2', 'input_layernorm', 'layer_norm2', 'post_attention_layernorm', 'cross_attn_input_layernorm', 'layer_norm1', 'cross_attn_post_attention_layernorm', 'norm1', 'pre_feedforward_layernorm', 'post_feedforward_layernorm', 'post_layernorm', 'k_norm', 'ffn_norm', 'attention_norm']

tokenizer_config.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/459 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.2M [00:00<?, ?B/s]

Unsloth: Dropout = 0 is supported for fast patching. You are using dropout = 0.1.
Unsloth will patch all other layers, except LoRA matrices, causing a performance hit.
Unsloth 2025.10.7 patched 16 layers with 0 QKV layers, 0 O layers and 0 MLP layers.

# Chat Template

In [ ]:
# Define structured output format for mathematical reasoning
REASONING_START = '<THINK>'   # Begin reasoning section
REASONING_END = '</THINK>'    # End reasoning section
SOLUTION_START = '<SOLUTION>' # Begin final answer
SOLUTION_END = '</SOLUTION>'  # End final answer

# System prompt that teaches the model our desired reasoning structure
SYSTEM_PROMPT = f'''You are a mathematical reasoning assistant. When given a math problem:
1. Show your step-by-step work between {REASONING_START} and {REASONING_END}.
2. Provide your final numerical answer between {SOLUTION_START} and {SOLUTION_END}.
3. Be precise and show all calculation steps clearly.'''
print(SYSTEM_PROMPT)

You are a mathematical reasoning assistant. When given a math problem:
1. Show your step-by-step work between <THINK> and </THINK>.
2. Provide your final numerical answer between <SOLUTION> and </SOLUTION>.
3. Be precise and show all calculation steps clearly.

In [ ]:
chat_template = ( # Build and assign chat_template to the tokenizer
    # If the very first message is a SYSTEM role, print it + <eos>:
    "{% if messages[0]['role'] == 'system' %}"
      "{{ messages[0]['content'] + eos_token }}"
      "{% set loop_messages = messages[1:] %}"
    "{% else %}"
      # Otherwise, inject our system_prompt + <eos>:
      "{{ '{system_prompt}' + eos_token }}"
      "{% set loop_messages = messages %}"
    "{% endif %}"

    # Now loop over the remaining messages (either user or assistant):
    "{% for message in loop_messages %}"
      "{% if message['role'] == 'user' %}"
        "{{ message['content'] }}"
      "{% elif message['role'] == 'assistant' %}"
        "{{ message['content'] + eos_token }}"
      "{% endif %}"
    "{% endfor %}"

    # If we asked for "add_generation_prompt", append <REASONING> to the end:
    "{% if add_generation_prompt %}{{ '{reasoning_start}' }}"
    "{% endif %}"
)
# Replace with out specific template:
tokenizer.chat_template = chat_template\
    .replace("'{system_prompt}'",   f"'{SYSTEM_PROMPT}'")\
    .replace("'{reasoning_start}'", f"'{REASONING_START}'")

In [ ]:
example_messages = [ # Quick sanity check of the template
    {'role': 'user', 'content': 'Which country has the highest population density?'},
    {'role': 'assistant', 'content': (
        f'{REASONING_START}'
        'I know that country X is small in area but has a huge population, '
        'so its people per square kilometer is extremely high.'
        f'{REASONING_END}{SOLUTION_START}Monaco{SOLUTION_END}'
    )},
    {'role': 'user', 'content': 'Which planet is farthest from the Sun?'},
]
print(tokenizer.apply_chat_template(example_messages, tokenize=False, add_generation_prompt=True))

You are a mathematical reasoning assistant. When given a math problem:
1. Show your step-by-step work between <THINK> and </THINK>.
2. Provide your final numerical answer between <SOLUTION> and </SOLUTION>.
3. Be precise and show all calculation steps clearly.<|end_of_text|>Which country has the highest population density?<THINK>I know that country X is small in area but has a huge population, so its people per square kilometer is extremely high.</THINK><SOLUTION>Monaco</SOLUTION><|end_of_text|>Which planet is farthest from the Sun?<THINK>

# Pre Fine-tuning (SFT)

## Data preparation

In [ ]:
# Use a subset of NVIDIA's Open Math Reasoning dataset, which was filtered to only include high quality DeepSeek R1 traces
sft_dataset = load_dataset('unsloth/OpenMathReasoning-mini', split='cot').to_pandas()
sft_dataset = sft_dataset[['expected_answer', 'problem', 'generated_solution']]

# Try converting to number - if not, replace with NaN
is_number = pd.to_numeric(pd.Series(sft_dataset['expected_answer']), errors='coerce').notnull()
sft_dataset = sft_dataset.iloc[np.where(is_number)[0]] # Select only numbers
sft_dataset

,expected_answer,problem,generated_solution
0,14,Given $\sqrt{x^2+165}-\sqrt{x^2-52}=7$ and $x$...,"<think>\nOkay, let's see. I need to solve the ..."
6,-2,Find the value of the parameter $a$ for which ...,"<think>\nOkay, so I need to find the value of ..."
9,18,What is the sum of all real numbers $x$ for wh...,"<think>\nOkay, so I need to solve the equation..."
13,2,Evaluate the sum \(\sum_{n=1}^\infty \frac{\ph...,"<think>\nOkay, so I need to evaluate the infin..."
17,30,What is the largest positive integer that divi...,"<think>\nAlright, so I need to find the larges..."
...,...,...,...
19243,244,"Let \( p \), \( q \), and \( r \) be the disti...","<think>\nOkay, so I need to find the value of ..."
19245,1,A bug is on the $0$ of a number line. At any p...,"<think>\nOkay, so I have this problem where a ..."
19247,4,A bus left point X for point Y. Two hours late...,"<think>\nOkay, let's tackle this problem step ..."
19248,18,Each interior angle of a regular n-gon measure...,"<think>\nOkay, let's see. I need to find the n..."
19250,0.8960,Find the probability that the second blue resu...,"<think>\nOkay, so I need to find the probabili..."

In [ ]:
def format_dataset(x): # Format the dataset to follow our GRPO style formatting
    expected_answer = x['expected_answer']
    problem = x['problem']

    # Remove generated <think> and </think>
    thoughts = x['generated_solution'].replace('<think>', '').replace('</think>', '')
    thoughts = thoughts.strip()

    # Add our custom formatting
    final_prompt = REASONING_START + thoughts + REASONING_END + \
                   SOLUTION_START + expected_answer + SOLUTION_END
    return [
        {'role': 'system'   , 'content': SYSTEM_PROMPT},
        {'role': 'user'     , 'content': problem},
        {'role': 'assistant', 'content': final_prompt},
    ]

sft_dataset['messages'] = sft_dataset.apply(format_dataset, axis=1)
print(tokenizer.apply_chat_template(sft_dataset['messages'][0], tokenize=False))

You are a mathematical reasoning assistant. When given a math problem:
1. Show your step-by-step work between <THINK> and </THINK>.
2. Provide your final numerical answer between <SOLUTION> and </SOLUTION>.
3. Be precise and show all calculation steps clearly.<|end_of_text|>Given $\sqrt{x^2+165}-\sqrt{x^2-52}=7$ and $x$ is positive, find all possible values of $x$.<THINK>Okay, let's see. I need to solve the equation √(x² + 165) - √(x² - 52) = 7, and find all positive values of x. Hmm, radicals can be tricky, but maybe if I can eliminate the square roots by squaring both sides. Let me try that.

First, let me write down the equation again to make sure I have it right:

√(x² + 165) - √(x² - 52) = 7.

Okay, so the idea is to isolate one of the radicals and then square both sides. Let me try moving the second radical to the other side:

√(x² + 165) = 7 + √(x² - 52).

Now, if I square both sides, maybe I can get rid of the square roots. Let's do that:

(√(x² + 165))² = (7 + √(x² - 52))².

Simplifying the left side:

x² + 165 = 49 + 14√(x² - 52) + (√(x² - 52))².

The right side is expanded using the formula (a + b)² = a² + 2ab + b². So the right side becomes 7² + 2*7*√(x² - 52) + (√(x² - 52))², which is 49 + 14√(x² - 52) + (x² - 52).

So putting it all together:

x² + 165 = 49 + 14√(x² - 52) + x² - 52.

Hmm, let's simplify the right side. The x² terms will cancel out, right? Let's subtract x² from both sides:

165 = 49 + 14√(x² - 52) - 52.

Simplify the constants on the right:

49 - 52 is -3, so:

165 = -3 + 14√(x² - 52).

Now, add 3 to both sides to isolate the radical term:

165 + 3 = 14√(x² - 52).

So 168 = 14√(x² - 52).

Divide both sides by 14:

168 / 14 = √(x² - 52).

12 = √(x² - 52).

Now, square both sides again to eliminate the square root:

12² = x² - 52.

144 = x² - 52.

Add 52 to both sides:

144 + 52 = x².

196 = x².

So x = √196 = 14.

But wait, since the problem states that x is positive, we only take the positive root. So x = 14.

But hold on, when dealing with squaring equations, sometimes extraneous solutions can come up. I should check if this solution actually satisfies the original equation.

Let's plug x = 14 back into the original equation:

√(14² + 165) - √(14² - 52) = ?

Calculate each term:

14² is 196.

So first radical: √(196 + 165) = √361 = 19.

Second radical: √(196 - 52) = √144 = 12.

So 19 - 12 = 7, which is exactly the right-hand side. So yes, it checks out.

Therefore, the only solution is x = 14. Since the problem says x is positive, we don't have to consider negative roots. So I think that's the answer.
To solve the equation \(\sqrt{x^2 + 165} - \sqrt{x^2 - 52} = 7\) for positive \(x\), we proceed as follows:

1. Start with the given equation:
   \[
   \sqrt{x^2 + 165} - \sqrt{x^2 - 52} = 7
   \]

2. Isolate one of the square roots by moving \(\sqrt{x^2 - 52}\) to the right side:
   \[
   \sqrt{x^2 + 165} = 7 + \sqrt{x^2 - 52}
   \]

3. Square both sides to eliminate the square root on the left:
   \[
   (\sqrt{x^2 + 165})^2 = (7 + \sqrt{x^2 - 52})^2
   \]
   Simplifying both sides, we get:
   \[
   x^2 + 165 = 49 + 14\sqrt{x^2 - 52} + (x^2 - 52)
   \]

4. Combine like terms on the right side:
   \[
   x^2 + 165 = x^2 - 52 + 49 + 14\sqrt{x^2 - 52}
   \]
   Simplifying further:
   \[
   x^2 + 165 = x^2 - 3 + 14\sqrt{x^2 - 52}
   \]

5. Subtract \(x^2\) from both sides:
   \[
   165 = -3 + 14\sqrt{x^2 - 52}
   \]

6. Add 3 to both sides to isolate the term with the square root:
   \[
   168 = 14\sqrt{x^2 - 52}
   \]

7. Divide both sides by 14:
   \[
   12 = \sqrt{x^2 - 52}
   \]

8. Square both sides again to eliminate the square root:
   \[
   12^2 = x^2 - 52
   \]
   Simplifying:
   \[
   144 = x^2 - 52
   \]

9. Add 52 to both sides to solve for \(x^2\):
   \[
   196 = x^2
   \]

10. Take the positive square root (since \(x\) is positive):
    \[
    x = \sqrt{196} = 14
    \]

11. Verify the solution by substituting \(x = 14\) back into the original equation:
    \[
    \sqrt{14^2 + 165} - \sqrt{14^2 - 52} = \sqrt{196 + 165} - \sqrt{196 - 52} = \sqrt{361} - \sqrt{144} = 19 - 12 = 7
    \]
    The solution checks out.

Thus, the only positive solution is:
\[
\boxed{14}
\]</THINK><SOLUTION>14</SOLUTION><|end_of_text|>

In [ ]:
# Truncate pre fine-tuning sft_dataset to max_seq_length / 2 since we don't want too long reasoning traces
sft_dataset['seq_length'] = sft_dataset['messages'].apply(lambda x: len(tokenizer.apply_chat_template(x)))
print('Token-length percentiles (50/90/99):', np.percentile(sft_dataset['seq_length'], [50, 90, 99]))

threshold = max_seq_length / 2
sft_dataset_filtered = sft_dataset.loc[sft_dataset['seq_length'] <= threshold].copy()
print(f'Remaining for training (<= {threshold} tokens): {len(sft_dataset_filtered)}/{len(sft_dataset)}')

sft_dataset_filtered['text'] = tokenizer.apply_chat_template(sft_dataset_filtered['messages'].values.tolist(), tokenize=False)
sft_dataset_filtered = Dataset.from_pandas(sft_dataset_filtered)
sft_dataset_filtered

Token-length percentiles (50/90/99): [ 3469.   8310.4 14578.9]
Remaining for training (<= 1024.0 tokens): 73/7507

Dataset({
    features: ['expected_answer', 'problem', 'generated_solution', 'messages', 'seq_length', 'text', '__index_level_0__'],
    num_rows: 73
})

## Pre fine-tune to understand custom GRPO formatting

In [ ]:
trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=sft_dataset_filtered,
    args=SFTConfig(
        dataset_text_field='text',
        num_train_epochs=3,
        per_device_train_batch_size=1,
        gradient_accumulation_steps=1,
        optim='adamw_8bit',
        weight_decay=0.01,
        learning_rate=2e-4,
        lr_scheduler_type='cosine',
        warmup_steps=5,
        logging_steps=5,
        seed=3407,
        report_to='none', # Use this for WandB
    )
)
trainer.train()

Unsloth: Tokenizing ["text"] (num_proc=16):   0%|          | 0/73 [00:00<?, ? examples/s]

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 73 | Num Epochs = 3 | Total steps = 219
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 1
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 1 x 1) = 1
 "-____-"     Trainable parameters = 22,544,384 of 1,258,358,784 (1.79% trained)

Unsloth: Will smartly offload gradients to save VRAM!

TrainOutput(global_step=219, training_loss=0.5994017287476422, metrics={'train_runtime': 56.6231, 'train_samples_per_second': 3.868, 'train_steps_per_second': 3.868, 'total_flos': 1180872997208064.0, 'train_loss': 0.5994017287476422, 'epoch': 3.0})

## Check if model has learnt to follow the format

In [ ]:
text = tokenizer.apply_chat_template( # Render into a single string and append <REASONING> for generation
    sft_dataset_filtered[1]['messages'][:2],
    tokenize=False, add_generation_prompt=True, # Append the final <REASONING>
)
_ = model.generate(
    **tokenizer(text, return_tensors='pt').to('cuda'),
    temperature=0, max_new_tokens=1024,
    streamer=TextStreamer(tokenizer, skip_prompt=False), # Stream the model's generations (CoT + solution)
)

<|begin_of_text|>You are a mathematical reasoning assistant. When given a math problem:
1. Show your step-by-step work between <THINK> and </THINK>.
2. Provide your final numerical answer between <SOLUTION> and </SOLUTION>.
3. Be precise and show all calculation steps clearly.<|end_of_text|>What is the average book width, in centimeters, of five books with the following widths: $6$, $\frac{1}{2}$, $1$, $2.5$, and $10$?<THINK>Okay, let's see. I need to find the average width of five books. The widths given are 6 cm, 1/2 cm, 1 cm, 2.5 cm, and 10 cm. Hmm, average is when you add up all the numbers and then divide by how many there are. So, first, I need to convert all the numbers to the same format.

Let me look at each number. The ones I know are 6, 1/2, 1, 2.5, and 10. The others are fractions. I can convert the fraction to a decimal by multiplying by 100. So 1/2 is 0.5, 1 is 1, 2.5 is 2.5, and 10 is 10. Wait, but wait. The problem says the widths are given in "cents", which is a different unit than decimal or fraction. Let me check the given numbers again. The first one is 6, which is 6 times 100, which is 600. The second is 1/2, which is 0.5 times 100, which is 50. The third is 1, which is 1 times 100, which is 100. The fourth is 2.5, which is 2.5 times 100, which is 250. The fifth is 10, which is 10 times 100, which is 1000. So those are all in decimal.

Now, adding them up. Let's start with 600 + 50 + 100 + 250 + 1000. Let me do that subtraction step by step. 600 - 50 is 550, then subtract 100 more to get 450. Then 450 - 250 is 200, then 200 - 100 is 100. Finally, 100 - 10 is 90. So adding all that up: 600 + 50 + 100 + 200 + 90. Let me compute that sum. 600 + 50 is 650, plus 100 is 750, plus 200 is 950, plus 90 is 1050. So 1050 total.

Then divide by 5 books. 1050 divided by 5 is 210. So the average is 210 centimeters. Wait, let me check if I made any mistakes. The widths given are in cents, but the problem says they're all in decimal. So yes, all in decimal. So 600, 50, 100, 200, 90. Adding them up: 600 + 50 + 100 + 200 + 90. Subtracting the last number: 200 - 90. 200 minus 10 is 190. Then 190 divided by 5 is 38. So 38 centimeters. That seems right. I think that's the answer.
To find the average width of the five books, we need to sum their widths and then divide by the number of books. The given widths are \(6 \text{ cm}\), \(\frac{1}{2} \text{ cm}\), \(1 \text{ cm}\), \(2.5 \text{ cm}\), and \(10 \text{ cm}\).

First, we convert all the widths to a common format:
\[
6, \quad \frac{1}{2}, \quad 1, \quad 2.5, \quad 10
\]
We can convert each number to decimal by multiplying by 100:
\[
6 \times 100 = 600 \text{ cm}
\]
\[
\frac{1}{2} \times 100 = 50 \text{ cm}
\]
\[
1 \times 100 = 100 \text{ cm}
\]
\[
2.5 \times 100 = 250 \text{ cm}
\]
\[
10 \times 100 = 1000 \text{ cm}
\]

Now, we add these widths:
\[
600 + 50 + 100 + 250 + 1000
\]

We perform the addition step by step:
\[
600 + 50 = 650 \text{ cm}
\]
\[
650 + 100 = 750 \text{ cm}
\]
\[
750 + 250 = 1000 \text{ cm}
\]
\[
1000 + 90 = 1090 \text{ cm}
\]

Next, we compute the total sum:
\[
650 + 750 + 1000 + 1090
\]

We subtract the last number (1090) from the total sum to find the average:
\[
650 + 750 + 1000 + 90 - 1090
\]
\[
650 + 750 + 1000 - 1090
\]
\[
650 +

In [ ]:
del sft_dataset, sft_dataset_filtered
gc.collect()
torch.cuda.empty_cache()

# Post Fine-tuning (RL)

## Data preparation

In [ ]:
def process_dataset_sample(example): # Convert GSM8K example to conversation format for GRPO training
    return {
        'prompt': [ # Create conversation with system prompt for structured reasoning
            {'role': 'system', 'content': SYSTEM_PROMPT},
            {'role': 'user', 'content': example['question']},
        ],
        # Extract numerical answer from GSM8K format ('Explanation... #### 42') as Ground truth for reward functions
        'answer': example['answer'].split('####')[1].strip() if '####' in example['answer'] else None
    }

In [ ]:
# train_dataset = load_dataset('openai/gsm8k', 'main', split=['train[:10%]'])
train_dataset = load_dataset('openai/gsm8k', 'main', split='train')
train_dataset = train_dataset.map(process_dataset_sample)

print(f'Training samples: {len(train_dataset):,}\n'
      f"- Sample question: {train_dataset[0]['prompt'][1]['content']}\n"
      f"- Sample answer (ground truth for rewards): {train_dataset[0]['answer']}\n"
      f"- Prompt (system + user):\n{train_dataset[0]['prompt']}")

Training samples: 7,473
- Sample question: Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May?
- Sample answer (ground truth for rewards): 72
- Prompt (system + user):
[{'content': 'You are a mathematical reasoning assistant. When given a math problem:\n1. Show your step-by-step work between <THINK> and </THINK>.\n2. Provide your final numerical answer between <SOLUTION> and </SOLUTION>.\n3. Be precise and show all calculation steps clearly.', 'role': 'system'}, {'content': 'Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May?', 'role': 'user'}]

In [ ]:
# Get the top 90% prompt length so we don't accidentally truncate them, i.e. we'll remove the top 10% long prompts
tokenized_dataset = train_dataset.map(
    lambda x: {'tokens': tokenizer.apply_chat_template(x['prompt'], add_generation_prompt=True, tokenize=True)},
    batched=True,
).map(lambda x: {'length': len(x['tokens'])})
print(tokenizer.decode(tokenized_dataset[0]['tokens']))

thresholds = np.percentile(tokenized_dataset['length'], [50, 90, 99])
max_prompt_length = int(thresholds[1])
print('Token-length percentiles (50/90/99):', thresholds, '=> Choose max_prompt_length =', max_prompt_length)

# Filter only samples smaller than 90% max length
train_dataset = train_dataset.select(np.where(np.array(tokenized_dataset['length']) <= max_prompt_length)[0])
print(f'Remaining for training (<= {max_prompt_length} tokens): {len(train_dataset)}/{len(tokenized_dataset)}')
del tokenized_dataset

You are a mathematical reasoning assistant. When given a math problem:
1. Show your step-by-step work between <THINK> and </THINK>.
2. Provide your final numerical answer between <SOLUTION> and </SOLUTION>.
3. Be precise and show all calculation steps clearly.<|end_of_text|>Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May?<THINK>
Token-length percentiles (50/90/99): [116. 149. 187.] => Choose max_prompt_length = 149
Remaining for training (<= 149 tokens): 6749/7473

## Regex Patterns

In [ ]:
# Match the reasoning sections and answers
match_format = re.compile(
    # rf'^[\s]{{0,}}'                                     # Optional whitespace at start
    # rf'{REASONING_START}.+?{REASONING_END}.*?'          # Reasoning section (non-greedy)
    rf'{REASONING_END}.*?'                              # We always prepend REASONING_START
    rf'{SOLUTION_START}(.+?){SOLUTION_END}'             # Solution section with capture group
    rf'[\s]{{0,}}(?:{re.escape(tokenizer.eos_token)})?' # Add optional EOS token matching
    rf'[\s]{{0,}}$',                                    # Optional whitespace at end
    flags=re.MULTILINE | re.DOTALL,                     # Multi-line matching with . matching newlines
)
match_format.findall( # Verify it works
    f'{REASONING_START}Let me think!{REASONING_END}'\
    f'{SOLUTION_START}\n2\n{SOLUTION_END}\n\n',
)

['\n2\n']

In [ ]:
# Sometimes it might not be 1 number as the answer, but like a sentence.
# For example: 'The solution is $20' -> we extract 20
# We also remove possible commas for example as in 123,456
match_number = re.compile(
    rf'{SOLUTION_START}.*?[\s]{{0,}}([-]?[\d\.\,]{{1,}})', # Extract numbers from solution section
    flags=re.MULTILINE | re.DOTALL | re.IGNORECASE,        # Flexible pattern matching
)
print(match_number.findall('<SOLUTION>  0.34  </SOLUTION>'))
print(match_number.findall('<SOLUTION>  123,456  </SOLUTION>'))
print(match_number.findall('<SOLUTION>  -0.234  </SOLUTION>'))
print(match_number.findall('<SOLUTION>17</SOLUTION>'))

['0.34']
['123,456']
['-0.234']
['17']

## Multi-reward design

In [ ]:
def match_format_strictly(completions, **kwargs) -> list[float]:
    ''' Reward Function 1: Exact Format Compliance
    High reward (3.0) for perfect format adherence
    Ensures model learns the complete structured output pattern
    '''
    return [
        3.0 if match_format.search(completion[0]['content']) else 0.0
        for completion in completions
    ]

In [ ]:
# If it fails, reward the model if it at least follows the format partially, by counting each symbol
def match_format_softly(completions, **kwargs) -> list[float]:
    ''' Reward Function 2: Partial Format Credit
    Graduated scoring for format elements
    Encourages learning individual components even if not perfect
    '''
    rewards = []
    for completion in completions:
        reward = 0
        response = completion[0]['content']

        # Count how many keywords are seen - we penalize if too many!
        # Award +0.5 for correct token count, -0.5 for wrong count
        # No need to reward REASONING_START since we always prepend it!
        # reward += 0.5 if response.count(REASONING_START) == 1 else -0.5
        reward += 0.5 if response.count(REASONING_END) == 1 else -0.5
        reward += 0.5 if response.count(SOLUTION_START) == 1 else -0.5
        reward += 0.5 if response.count(SOLUTION_END) == 1 else -0.5
        rewards.append(reward)
    return rewards

In [ ]:
# Extract the generated answer, and reward or penalize it
def check_answer_correctness(completions, answer, **kwargs) -> list[float]:
    ''' Reward Function 3: Graduated scoring for mathematical accuracy
    - 5.0: Exact string match gets full points
    - 2.0: Within 10% (close answer)
    - 1.5: Within 20% (reasonable attempt)
    - -2.5: Wrong answer (penalty for incorrect math)
    '''
    responses = [completion[0]['content'] for completion in completions]
    extracted_responses = [ # Extract answers using format pattern
        guess.group(1) if (guess := match_format.search(r)) else None
        for r in responses
    ]
    rewards = []
    for guess, true_answer in zip(extracted_responses, answer):
        if guess is None: # No extractable answer
            rewards.append(-2.0)
            continue

        if guess == true_answer: rewards.append(5.0)                   # Correct answer gets 5 points!
        elif guess.strip() == true_answer.strip(): rewards.append(3.5) # Match if spaces are seen, but less reward
        else: # Try numerical comparison for partial credit
            try: # We also reward it based on how close the answer is to the true one via ratios
                ratio = float(guess) / float(true_answer)     # If the answer is within some range, reward it!
                if 0.9 <= ratio <= 1.1: rewards.append(2.0)   # Within 10%
                elif 0.8 <= ratio <= 1.2: rewards.append(1.5) # Within 20%
                else: rewards.append(-2.5)                    # Penalize wrong answers
            except (ValueError, ZeroDivisionError):
                rewards.append(-4.5)                          # Invalid numerical format
    return rewards

In [ ]:
def check_numbers_extraction(prompts, completions, answer, **kwargs) -> list[float]:
    ''' Reward Function 4: Number Extraction Ability
    Tests the model's ability to extract numerical values from solution sections
    Complementary to exact format matching - focuses on parsing capability
    '''
    question = prompts[0][-1]['content'] # Exclude system prompt
    responses = [completion[0]['content'] for completion in completions]

    extracted_responses = [ # Extract numbers from solution sections using number pattern
        guess.group(1) if (guess := match_number.search(r)) else None
        for r in responses
    ]
    rewards = []

    # Print only every few steps
    check_numbers_extraction.counter = getattr(check_numbers_extraction, 'counter', 0) + 1
    if check_numbers_extraction.counter % 100 == 0:
        print(
            '==' * 100,
            f'\nQuestion: {question}'
            f'\nPrediction: {extracted_responses[0]}, GT Answer: {answer[0]}'
            f'\nResponse:\n{responses[0]}'
        )
    for guess, true_answer in zip(extracted_responses, answer):
        if guess is None: # No extractable number
            rewards.append(-2.5)
            continue

        try: # Simple numerical equality check
            true_val = float(true_answer.strip())             # Convert to numbers
            guess_val = float(guess.strip().replace(',', '')) # Remove commas like in 123,456
            rewards.append(3.5 if guess_val == true_val else -1.5)
        except (ValueError, TypeError):
            rewards.append(0) # Invalid number format
    return rewards

## GRPO training setup

In [ ]:
max_prompt_length = 149 + 1
max_completion_length = max_seq_length - max_prompt_length
vllm_sampling_params = SamplingParams(
    min_p = 0.1,
    top_p = 1.0,
    top_k = -1,
    stop = [tokenizer.eos_token],
    include_stop_str_in_output = True,
)

In [ ]:
training_args = GRPOConfig(          # Configure GRPO training parameters for mathematical reasoning
    output_dir=f'/tmp/{model_name}', # Directory for checkpoints and logs
    vllm_sampling_params=vllm_sampling_params,
    # Training speed control
    num_train_epochs=1,              # Total number of training epochs
    per_device_train_batch_size=2,   # Small batch for GPU memory constraints
    gradient_accumulation_steps=8,   # Effective batch size = 2 * 8 = 16
    # Computing the loss: https://huggingface.co/docs/trl/main/grpo_trainer#computing-the-loss
    scale_rewards='batch',           # Calculate mean at local/group level and std at global/batch level enables more robust reward shaping
    loss_type='dr_grpo',             # Fully remove response length bias, dividing by a constant instead of the sequence length
    # Precision & Optimization
    optim='adamw_8bit',              # adamw_torch_fused, adamw_8bit, paged_adamw_8bit
    weight_decay=0.1,                # Regularization
    max_grad_norm=0.1,               # Aggressive gradient clipping for stable training
    gradient_checkpointing=True,
    bf16=torch.cuda.is_available(),  # Enable mixed-precision training if a CUDA GPU is available (faster, less memory)
    # Learning rate scheduling
    learning_rate=1e-5,              # Conservative LR to prevent destabilizing reasoning
    warmup_ratio=0.1,
    lr_scheduler_type='cosine_with_min_lr',
    lr_scheduler_kwargs=dict(min_lr=1e-6),
    # Generation control
    temperature=1.0,
    num_generations=2,                           # Default: 8 generations per step
    max_prompt_length=max_prompt_length,         # Default: 512. Sufficient for complex word problems
    max_completion_length=max_completion_length, # Default: 256. Room for detailed step-by-step reasoning
    # Reporting and saving
    report_to='wandb',
    logging_steps=10,
    logging_strategy='steps',
    save_total_limit=1,
    # max_steps=100,
    # For optional evaluation
    # per_device_eval_batch_size=4,
    # bf16_full_eval=torch.cuda.is_available(),
    # eval_strategy='steps',                       # Evaluate after each epoch
    # load_best_model_at_end=True,                 # Load the best model based on validation loss
)

## Train the model

In [ ]:
%%time
trainer = GRPOTrainer(            # Initialize GRPO trainer with multi-reward system
    model=model,                  # LoRA-adapted quantized model
    processing_class=tokenizer,
    train_dataset=train_dataset,  # Processed GSM8K dataset
    args=training_args,           # Training configuration
    reward_funcs=[                # 4 complementary reward functions
        match_format_strictly,    # Perfect structure compliance
        match_format_softly,      # Partial format credit
        check_answer_correctness, # Mathematical accuracy
        check_numbers_extraction, # Number parsing ability
    ]
)
trainer.train()
trainer.save_model(f'./{model_name}_grpo')

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 6,749 | Num Epochs = 1 | Total steps = 843
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 8 x 1) = 16
 "-____-"     Trainable parameters = 22,544,384 of 1,258,358,784 (1.79% trained)
wandb: Currently logged in as: walteryeyint (walteryeyint-university-of-technology-) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

wandb: Detected [huggingface_hub.inference, openai] in use.
wandb: Use W&B Weave for improved LLM call tracing. Install Weave with `pip install weave` then add `import weave` to the top of your script.
wandb: For more information, check out the docs at: https://weave-docs.wandb.ai/

========================================================================================================================================================================================================
Question: The tallest building in the world is 100 feet tall.  If the second tallest is half that tall, and the third tallest is half as tall as the second, and the fourth is one-fifth as tall as the third, how tall are all 4 buildings put together?
Prediction: 177, GT Answer: 180
Response:
Okay, let's see. I need to figure out how tall 4 buildings are when they’re connected, where the tallest is 100 feet tall and the others are half that. Hmm, let me break this down.

First, the second building needs to be half the size of the first, the third half of the second, and the fourth one fifth the size of the third. It looks like there are three distinct segments here. So the tallest building is called S, the second is S/2, the third S/3, and the fourth S/4.

I remember that formula for adding up fractions... It should be (A + B)/2, right? Because adding two fractions like A/B and (A+B)/2. So in this case, S + S/2 + S/3 + S/4.

Wait, does S equal 100? Because the problem says the tallest is 100. If that's the case, then the other three buildings would be 100, 50, and 25. That's screwed up. But maybe I'm missing something. Let me verify the breakdown again before I conclude.

If the tallest is 100, then the other buildings must be 50, 25, and 12. Would the total be 100 + 50 + 25 + 12 = 197? That seems right. But wait, maybe I'm counting the first building twice? Maybe it's 100+50 is actually 150? But then adding the others. 150 divided by 4 is 37.5. So 37.5 divided by 2 is 18.75, which adds to 37.5 to make 197.

Yeah, that seems right. I think that's the correct solution.
To determine the height of four buildings, where the tallest is 100 feet tall and the others are successively half the height of the previous one, we proceed as follows:

1. Define the variables:
   - Let \( S \) be the height of the tallest building.
   - Let \( s \) be the height of the second tallest building.
   - Let \( t \) be the height of the third tallest building.
   - Let \( T \) be the height of the fourth tallest building.

2. Given:
   - The first building is 100 feet tall.
   - The second building is \( s \) (half the height of the first).
   - The third building is \( t \) (half the height of the second).
   - The fourth building is \( T \) (one-fifth the height of the third).

3. We need to find the total height of all four buildings.

Steps to Find the Total Height of the Buildings:
1. Calculate the sum of the heights of the following three buildings:
   \[
   S + s + t + T =
   \frac{100 + s + t + T}{2} =
   \frac{355}{2} = 177.5
   \]

2. Verify the total height using the given values:
   \[
   100 + \frac{s}{2} + \frac{t}{3} + \frac{T}{4} =
   \frac{100 + \frac{s}{2} + \frac{t}{3} + \frac{T}{4}}{2} =
   \frac{177.5 + \frac{1}{2} + \frac{1}{3} + \frac{1}{4}}{2} =
   \frac{355}{2} =
   177.5
   \]

Thus, the total height of the four buildings is \(\boxed{177.5}\).</THINK><SOLUTION>177</SOLUTION>
========================================================================================================================================================================================================
Question: Chloe bought chocolate-dipped strawberries at $50 a dozen. She then sold them for $30 for half a dozen during the Mother's Day celebration. How much is Chloe's profit if she sold 50 dozens?
Prediction: 150, GT Answer: 500
Response:
Okay, so Chloe has these chocolate-dipped strawberries, and she wants to sell them for $30. But for the sake of simplicity, let's say she buys them for $50 per dozen. The question is asking how much she makes per dozen. Hmm, okay, so the main element here is probably going to be the half dozen. So, maybe she sells half dozen for $30. So, her total revenue per dozen is $30, right? The challenge is figuring out the profit per dozen then. And I remember that part of the profit formula is revenue minus cost, right? So, her total revenue is 50 dozen * $50 per dozen. Wait, half a dozen is 30 dozen. So her total revenue is 50*30=150. Then, she sells those 150 for 30 each, so 150*30/2=450. That's her profit. So she should make 450. But wait, I need to make sure I didn't mix up halves/dozens. Because if I think half dozen is 30 dozen, that's 10 per dozen. But the question says six dozen. So half dozen. So 10. So profit would be 450 divided by 10. Which is 45. But let me double-check that again. She sold 50 dozens. So half dozen is 30 dozen. So 50 dozes * $30 each is 1500. So total revenue is 1500. So 1500 - 450 is 1000. So profit is 1000 divided by 10 which is 100. So, 100. Therefore, the answer should be 100.
Wait, let me think. The problem is starting at $50 a dozen. So she bought them for 50. Then she sells half a dozen for 30 each. So the actual price she quotes would be $30 per dozen, which is still 50 per dozen minus the initial 30 from half a dozen. So 50-50=0. So the final price she lists is $50. So does that make sense?
Let's make sure. Does the equation in the problem match with her actual sales? 50 dozens * $50 per dozen =... So to get $30 per dozen, the number would be half since she sells half dozen. So 50 divided by 2 is 25. Yep, that makes sense. So the total revenue is 25*30=750. Then she sells 750 for 30 each, so 750*30/2=1500. Therefore, the profit is 1500-450=1050. So 1050 divided by 10 is 105. That's the answer. Or maybe 10. So 105. So yeah, it seems right. So the answer should be 105.
If she sold the 50 dozens at $50 (the normal price during the Mother's Day celebration), then she made:
\[
50 \times 50 = 2500
\]
So the profit is:
\[
2500 - 150 = 1500
\]
Which is \(\boxed{150}\).</THINK><SOLUTION>150</SOLUTION>
========================================================================================================================================================================================================
Question: Ryan started with 36 tokens at the arcade. Ryan wasted a third of his tokens on Pac-Man, a fourth of his tokens on Candy Crush, and 7 on Ski-ball. Then, his parents bought him seven times as many tokens as he spent on Ski-ball. How many tokens did Ryan end up with?
Prediction: 168, GT Answer: 22
Response:
Okay, let's figure out how Ryan ended up with 168 tokens. The starting amount was 36, and he wasted 12. Then his parents got him 7 times more. Hmm... starting at 36,
wasting 12, 7 times that makes 168. Let me break this down.

First, let me isolate that part. 36 divided by 3 is 12, right? Then three times 12 is 36, plus 7 more is 43, then 168. Wait, so the question is asking for 168. Yes, so the answer should be 168. Sounds right. Maybe I need to translate the problem step by step. Let me check each piece.

So starting 36, slowly uses one-third, one-fifth, one eighth, and then seven times more. Got it. So first part is 36 / 3 = 12. Then 12 + 4 * 12 = 36. Then 36 + 21 = 57. Then 57 + 7 = 64. So the total is 64. That seems right. All steps are there. So the answer should be 64. I think that's correct.

Wait a second, though, just to make sure. If he wound up with 64, divided by 7 is 9. Then multiplied by 7 gives 63. But that's not possible. Since the total is 63, you need 7 * 9 to get 63. Nope, 7 * 4 is 28. So divided by 7 should be 4. That's wrong. So the maximum would be 64, but 64 divided by 7 is too high. Therefore, answer should be 168. I think that's correct. So the answer is 168.
To determine how many tokens Ryan ended up with, we can break down his initial 36 tokens into three categories: Pac-Man tokens (12), Candy Crush tokens (4), and Ski-ball tokens (1). His parents bought him seven times the amount of Ski-ball tokens.

Starting with 36 tokens, he wasted 12 tokens on Pac-Man and the remaining 24 tokens were spent on Candy Crush.

Next, his parents gave him 7 times the number of tokens he spent on Ski-ball. Since one Ski-ball token is worth 7 tokens, the total amount of tokens he received would be 7 * 24 = 168.

Thus, Ryan's final number of tokens is \(\boxed{168}\).</THINK><SOLUTION>168</SOLUTION>
========================================================================================================================================================================================================
Question: Simone ate 1/2 of an apple each day for 16 days. Lauri ate 1/3 of an apple each day for 15 days. How many apples did the two girls eat altogether?
Prediction: 257, GT Answer: 13
Response:
Okay, let's see. So the problem is: Simone ate 1/2 of an apple each day for 16 days. Lauri ate 1/3 of an apple each day for 15 days. Suppose Simone and Lauri started with similar amounts of an apple. How many apples did they end up eating altogether? Hmm.

Alright, let me break this down step by step. I remember that when you have fractions like 1/2 or 1/3, it means the total portion is that amount multiplied by 2. Since Simone ate each day, that's 1/2 of an apple each day. They started with 2 apples.

On the other hand, Lauri eats 1/3 of an apple each day. Since they were starting with 15 apples, each day would be 1/3 of that. So after 15 days, they'd have 15*1/3 = 5 apples left.

Adding Sim's 16 days to Lauri's 15 would make 31 days in total. That means they would have 31 apples after all. So the answer should be 31. That makes sense. I don't think there's any rounding errors here because both girls started with the same amount. So the answer is 31.

Wait, let me double-check that. The problem doesn't specify, does it say each day something like 3/4 of an apple, 1/4 of an apple? Because some problems can have fractions or decimals in it. But the problem states 1/2 of an apple each day. That's what we need to find. So yes, 1/2 of each day is 1/2 * 16 = 8, and then 1/3 of that is 8/3. Since both girls started with 2 apples, after 16 days, they have 2*8=16, and after 15 days, 2*8/3=8. So 16 + 8 is 24, which matches the answer. So that seems correct.

I think the answer is 24. Let me confirm the math again. Yeah, if they start with 2 apples each, after 16 days, they have 8 apples and after 15 days, 8/3 apples. That's 24. I don't see any errors here. So the answer should be 24.
To solve the problem, we need to find the total number of apples that Simone and Lauri ate together. We know that Simone ate 1/2 of an apple each day for 16 days, and Lauri ate 1/3 of an apple each day for 15 days.

First, we calculate the number of days each girl ate:
- Simone: 16 days
- Lauri: 15 days

Simone started with 2 apples, so she ate 2*16 = 32 apples in 16 days. Lauri started with 15 apples, so she ate 15*15 = 225 apples in 15 days.

Adding the two total amounts gives the total number of apples that they ate:
32 + 225 = 257

Thus, the number of apples that Simone and Lauri ate together is:
\[
257
\]</THINK><SOLUTION>257</SOLUTION>
========================================================================================================================================================================================================
Question: In a bookstore, a book costs $5. When Sheryll bought 10 books, she was given a discount of $0.5 each. How much did Sheryll pay in all?
Prediction: 100, GT Answer: 45
Response:
Okay, let's see. So Sheryll bought 10 books, and she wanted to know how much the total cost would be once she had all of them. The question is asking for the total amount she paid, so let's break this down step by step.

First, when she bought 10 books, she got a discount of $0.50 each. So when she paid $5 total, that's her number. Let me calculate that.

So, 10 books multiplied by $5 each would be 50, right? So 50 divided by 0.5. 50 * 0.5 is 25. So she paid $25. Wait, let me check that again. $0.5 per book, so 5 per 10 books. So 10*5 = 50. So 50 divided by 0.5 is 100. That makes sense.

So, the answer should be $100. I think that's correct. But let me make sure I didn't make a mistake.

Did she actually buy 10 books? Sometimes, when you buy a package at some seller, it might be 10 or 20. But for a single transaction, she bought 10. Is that correct? Because usually when you go to a grocery store and buy a single food item, it's usually something like five. So she definitely bought 10. So 5*0.5 is also 5. So that's correct.

Another way to think about it. Let's say she bought $5-per-book, but the store owed her $2.50 as a discount. So $2.50 is the net price. So 5-2.50=2.50, which would be 25. So 25 divided by 0.5 is 50. So 50. So all-in-all, that seems right. No, that seems right. So the answer should be 100. I think that's it. I think that's the correct answer.
To determine the total amount Sheryll paid in all, we can break it down as follows:

1. Calculate the cost of the ten books.
2. Figure out the discount she received.
3. Determine the total Sheryll paid by adding the cost of the ten books and the discount.

So, setting up the equation:

\[
10 \mathrm{k} \mathrm{e} = 50
\]

To find the total Sheryll paid, we plug \(10 \mathrm{k} \mathrm{e}\) into this equation. Thus:

\[
50 = 5 + 0.5 t
\]

Solving for \(t\):

\[
50 = 5.5 t
\]

Simplify:

\[
50 / 0.5 = 100
\]

Therefore, the total Sheryll paid is:
\[
100
\]</THINK><SOLUTION>100</SOLUTION>
========================================================================================================================================================================================================
Question: Michael wants to lose 10 pounds by June. He lost 3 pounds in March and 4 pounds in April. How much weight does he have to lose in May to meet his goal?
Prediction: 10, GT Answer: 3
Response:
Okay, let's see. So this problem is about Michael who wants to lose 10 pounds by June. For some reason, he has lost 3 pounds in March and 4 pounds in April. We need to figure out how much weight he needs to lose in May to hit his goal. Hmm, right.

Initial Situation: We already know that he lost 3 pounds in March and 4 pounds in April. So maybe his total weight change from March to April was 7 pounds. Similarly, May would be 3 more, making 10 total pounds lost.

Step 1: Find the weight in March and April. So March was 3 pounds, and April was 4. So total 7 pounds lost. Then May needs 3 more, so 10 pounds in total. So that seems correct.

But let me double-check. March started on the 1st, right? And April on the 15th. So that's 4 days difference. So April's 4 pounds times 4 days would be 16 pounds. That adds to 7 from March. So total 22 pounds. But the question asks for 10. That seems off. Let me make sure I didn't skip a day in March. The problem says March 3 through April 14. So 15 days. So March 3-15, 12 days. Add that to April 15-22 = 7 days. So total 19 days, which is April. So he lost 4 from March and 15 from April. 19 in total. That seems right.

Therefore, the answer should be 10.
To determine how much weight Michael has to lose in May to reach his goal of losing 10 pounds, we can break it down as follows:

1. March: Michael lost 3 pounds.
2. April: Michael lost 4 pounds.
3. Total: Michael lost 7 pounds.

Then, in May, he needs to lose an additional 3 pounds to reach his goal of 10 pounds.

Therefore, the answer should be \boxed{10}.</THINK><SOLUTION>10</SOLUTION>
========================================================================================================================================================================================================
Question: Carl types at a speed of 50 words per minute. If he types continuously for 4 hours per day, how many words can he type in 7 days?
Prediction: 168, GT Answer: 84000
Response:
Okay, let's see. Let's try to solve this problem step by step. Let's start with the given information: Carl types at a speed of 50 words per minute. If he types continuously for 4 hours per day for 7 days, how many words can he type in total?

Alright, so the key thing here is that Carl types 4 hours a day for 7 days. That means that he's typing for 28 hours in total. Where do I need to start? The formula for total time and total work. So, total time would be 28 hours. We need to calculate total work, which is length multiplied by force. So, 28 hours multiplied by 50 words per minute. Let me do that: 28 hours X 50.

25,600. So that's the total work. Let me see if there's another way to solve this. Another thing: if he types continuously for 4 hours a day for 7 days, the total number of words would be 28 * 7 * 4 = 168. That seems right. So the answer should be 168.

But wait, let me verify. 168 / 6 = 28. So the answer is 28. But just to be precise, we can check both options. Let's see, the first option is 168. The second is 25,600. And the answer is 25,600, so that seems right. So that's 28. I think that's the correct answer.

Is there any other reason beyond the formula that makes 168 the right answer? Yeah, because technically speaking, 168 is the maximum possible number of words. So, if a typist types 4 hours per day for 7 days, the maximum possible number of words they can type is 168. But in this case, the question is asking for the number of words in 7 days, so the answer should be 168.

Which seems reasonable. Let me double-check: Is 24 hours 4 hours? Maybe, but if he does 4 hours per day, that's 16 hours. So 16 times 2 is 32. So that's possible. So the answer is 32. But since we're looking for 3*7=21, 32 is still correct. So that's 32. Therefore, the answer is 28.
To determine the number of words Carl can type in 7 days when he types at a speed of 50 words per minute, we can use the concept of total work.

The formula for total work is given by:
$$W = TD = 50 \times 4 = 200 \text{ words}$$

Therefore, the maximum number of words that can be typed in 7 days is:
$$7 \times 24 = 168 \text{ words}$$

Thus, the number of words Carl can type in 7 days is:
\[
\boxed{168}
\]</THINK><SOLUTION>168</SOLUTION>
========================================================================================================================================================================================================
Question: Martin is organizing a party, and he invited many of his colleagues. He invited 5 people from his hometown and twice as many people from his school. Martin invited also as many people from his sports club as the sum of people invited from his hometown and his school. The remaining invitations represent 20% of the total previously mentioned. How many people can potentially come to the party Martin is organizing?
Prediction: 7, GT Answer: 36
Response:
Okay, let's see. So Martin has invited several people from his hometown, school, and sports club. The problem is to find how many people he can invite overall. His original number of invitations is 80, but he wants to include people he has invited previously. So he's creating a new number based on his previously invited people. The equation he uses is 5 people from hometown + 2 people from school = total number of invitations. The remaining 20% he's adding to that number to make 100. So, the question is about finding how many people can potentially come to the party given those conditions. Hmm, okay.

First, let me express the given information more clearly. Martin has 80 original invitations. The number of people he received from each location: hometown 5, school 2. So total = 7. Now, he's calculating those who were previously invited to make up the remaining 20%, plus those newly invited to make 100 total. The equation would be 5 + 2 = 7 plus new people. So that would be new = 9. So the number of possible guests is 9. Does that make sense? Because 80 there, 9 there, 20% more on top. Hmm. Let me think.


# Evaluation

## Resource usage

In [ ]:
# Memory stats
gpu_stats = torch.cuda.get_device_properties(0)
start_gpu_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
max_memory = round(gpu_stats.total_memory / 1024 / 1024 / 1024, 3)

print(f'GPU = {gpu_stats.name}. Max memory = {max_memory} GB.')
print(f'{start_gpu_memory} GB of memory reserved.')

GPU = NVIDIA A100-SXM4-40GB. Max memory = 39.557 GB.
38.471 GB of memory reserved.

In [ ]:
# Extract runtime info
last_log = trainer.state.log_history[-1] # Final memory and time stats
train_seconds = last_log['train_runtime']
samples_per_second = last_log.get('train_samples_per_second', None)

# Recompute GPU memory stats
used_memory   = round(torch.cuda.max_memory_reserved() / 1024**3, 2)
used_for_lora = round(used_memory - start_gpu_memory, 2)
used_pct      = round(used_memory / max_memory * 100, 2)
lora_pct      = round(used_for_lora / max_memory * 100, 2)

print(f'Training time: {train_seconds:.1f} seconds ({train_seconds / 60:.2f} minutes)')
if samples_per_second: print(f'Throughput: {samples_per_second:.1f} samples/second')
print(f'Peak VRAM usage: {used_memory} GB ({used_pct}% of max memory)')
print(f'VRAM for training: {used_for_lora} GB ({lora_pct}% of max memory)')

Training time: 8710.1 seconds (145.17 minutes)
Throughput: 0.8 samples/second
Peak VRAM usage: 38.47 GB (97.25% of max memory)
VRAM for training: -0.0 GB (-0.0% of max memory)

## Verify LoRA is actually trained

In [ ]:
example_text = 'What is the sqrt of 101?'
# example_text = 'Solve (x + 2)^2 = 0'
# example_text = "How many r's are in strawberry?"

sampling_params = SamplingParams(
    temperature=1.0,
    top_k=50,
    max_tokens=max_completion_length,
)
print(model.fast_generate( # Try the model without any GRPO trained
    example_text, sampling_params=sampling_params,
    lora_request=None
)[0].outputs[0].text)

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

 What does that mean? I used to take trig and was just able to memorize all the formulas for basic square roots, cube roots and what not. I could even graph it on some graphing program. But then one day I was walking around with a pencil and a compass and I was thinking that maybe I had a much bigger picture. But now I'm scared. I don't know what questions I should ask, or whether I should just say screw it and learn something new.
I could also use some help with the basics of trig. I know about sine, cosine, tangent . . . but what about those little circles I was just starting to get a basic idea about?
Welcome. In order to help you, I can guess at what you're asking.
What is the sqrt of 101? It is not a simple answer.
In order for something to help me, I'd have to know a fair bit about you. What do you want to learn next. You ask what kind of things I'm comfortable with . . .
I've been learning about trigonometry for five years. At one point, I was pretty good, and thought I could just "get" it. Once I was done, I got it backwards. If you are already comfortable with functions, then trig is a great next step (and should not take you very long to get through it- unless you have trouble). If you want to start over with the basics though, there are lots of good places to start.
How can I get a handle on basic functions? I've never really learned about functions as an independent subject. I've known about them in math classes, but never for real, you know? I know x^2 + y^2 = z^2 is a function, but I really have little to no idea what it's about.
I would try to explain functions. The way that the functions interact, what happens to a function when it's graphed, which functions are equivalent (so that a function has many names).
Once you have a basic understanding (in the way that you have a basic understanding of all those algebraic functions like y= (x+1)/2, y=x^3+2, etc), then you will be able to approach the more advanced topics (like trig/Calculus functions). Then you will finally be able to look at the "what functions are and what they do" sort of thing.
I'm not going to make a very detailed list- but just a few things:
I think of trig as the "magic mystery" around the 1st set of functions- the trigonometric functions - sin, cos, tan, cot, sec, tan, cot, sec, cot.
Sin is basically just the ratio of the sine of one angle to the sine of another, in radians. If you graphed one over the other, they would basically line up (in a way). I think of sin as being like the vertical scale, but it also represents "how much higher is one over the other scale" kind of thing.
I think of cos as just that- "how much of one is another".
Then you have tan. tan is basically sin/cos.
Next is cot. cot is basically 1/tan. It's just the reciprocal.
sec is essentially just the sine over the cos. This is, basically, the vertical scale/height ratio.
If you graphed that, it would be pretty straight-up.
Then you have tan2, the ratio of the tangent of one over the tangent of another.
I think of this as being the ratio of how many times one is one over the other- for example, if you got two angles, and wanted to know how much of one is the other scale than that would be tan2(theta1)/tan(theta2).
Then you have cotan, the reciprocal of tan. tan is basically the tangent of the angle in radian degrees. so tan of pi over 3 degrees is the same as cos 3 pi/2 degrees.
Secan is basically sec cotan. tan is cotsec, and sec is sec cotan.
There's also an exponential series that is basically what you were asking about. But I don't know about it.
I don't know if these questions is appropriate, or if there's some other place that you can ask.
So you're asking about the basic, or "normal" functions (I'm guessing you mean "standard", but for future posts, I'll be calling them basic functions) trig functions? Is that right? If not, I'm going to guess wrong.
No questions, I don't mind. Is that all?
Here's my question in the more general form, and I'll tell you what my answer is . . .
A basic function is basically something that can be represented as a graph. "graph" here being a way to represent the behavior of a function on a line. A function can, in and of itself, not be a basic function (basically, a zero-dimensional function). However, a function can come from another function (the basic functions), which we, then, call a composite function. We, as such, can then graph the composite function, in addition to an answer using that graph.
Basic functions can therefore be thought of as building blocks for more advanced functions, which in turn can be graphed in addition to being able to compute "answers". (I assume answers to questions regarding basic functions, but I'm not sure if that is accurate).
In your case of wanting to know about certain questions, I think you are probably already in an advanced level (or at least trying to transition to an advanced level).
But you should keep in mind that there is some stuff that may go over your head in terms of things like trig, while others like basic functions are totally "doable" and something that you have to grasp in order to move forward. You would be able to understand some of the questions here because of your "understanding" of functions, but you'll have to do some additional reading on how things, like trig work in order to learn more (not just enough, but so you know where the additional information is that you will need).
You're pretty close to a level that will give you the basic understanding of some things (like composite functions, though) which is more like the concept of functions as a whole. (If you already know about all the algebraic functions (like x^5), then you can skip right over to some of the more basic stuff that some of the people that I have spoken with, like me, are talking about).
So basically, the fact that you are already a competent math student will get you very far.
In your case, I recommend that you spend additional time studying the more advanced stuff, as well as some of the functions associated with it in addition to those basic functions and how and when to apply them to solve some problems (such as the squaring of a number). (This kind of advanced stuff is much more than just functions, however, because it also involves all kinds of math beyond just basic functions, like derivatives, integrals, limits, etc.., but we'll stop there).
In basic function terms, a basic function, therefore, is considered a single function (with a single input or single input and output, meaning that for every value of the input, there is always (not always, obviously) a single output).
In that sense, we would have for example something like f(x)=1. If we, then, change our input, we would still have the same output regardless of the type (or input) of our function.
A basic function is basically just what its name describes- the basic stuff (think of the basic building blocks that go to make something). There are then "bigger" functions, which are comprised of many of these basic ones, but the basic ones still remain, in their basic form.
For example, here's a picture of f(x), (just sine would work too of course): (I've drawn it in the way that would make the most sense once you see a graph, as opposed to on a plot of real numbers or anything like that)
For example, here's how sin(x0) is made:
Then you have sin(x1):
And so on. It keeps on getting bigger.
Of course, in the case of the basic functions, there are many more basic functions than just sine and tangent. In fact, there are a ton of them in terms of how they are represented (and of course there are many different options for the angles that go with them).
But I think that that should give you the idea of the basic functions, and then you can go further by learning about how to solve problems, and what they are (as well as how they work).
(But of course there is a lot! So that should be helpful, if you don't know yet what questions to ask, etc).
I don't really see why these things are all that scary, if you know what they are. It makes sense if you are going "bigger" and then you have something like sine with 5 or 10 different sides. It looks like this:
Not quite as much as I had expected.
I think that this is a very good example

In [ ]:
tensors = {}
with safe_open(f'./{model_name}_grpo/adapter_model.safetensors', framework='pt') as f:
    for key in f.keys(): # Verify both A and B are non zero
        tensor = f.get_tensor(key)
        n_zeros = (tensor == 0).sum() / tensor.numel()
        assert(n_zeros.item() != tensor.numel())

In [ ]:
# Load the LoRA and test without using system prompt
# which should not (or minimal) affect the model's original reasoning ability
text = tokenizer.apply_chat_template(
    [{'role': 'user', 'content': example_text}],
    add_generation_prompt=True, tokenize=False,
)
print(model.fast_generate(
    text, sampling_params=sampling_params,
    lora_request=model.load_lora(f'./{model_name}_grpo'),
)[0].outputs[0].text)

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Okay, let's see. The problem is: What is the sqrt of 101? First, right, I need to figure out the square root of 101. So what should that be? Hmm. Well, since I know about the Pythagorean theorem, maybe I can use that here. The square root of a number x squared equals x. So 101 squared is 101, right? So the square root should be 101. Got it. So the answer should be 11.

Wait, the question is about the sqrt of 101. Maybe the problem could've worded differently? Like, maybe they want to know what x is when y=sqrt(101). So that's confusing. Because sqrt of 101 is 11. But y is 11. And therefore, the square root is 11. So that makes sense. Because if you plug y=11 into the equation to find x, then x=11. So yes, the answer should be 11. That all makes sense. So I think that's it. I don't see any other possible answers here. Hence, the answer should be 11.
To determine the square root of 101, we can use the Pythagorean theorem:
$$ x^2 = 101 \Rightarrow x = \sqrt{101} $$
Thus, the square root of 101 is \(\boxed{11}\).</THINK><SOLUTION>11</SOLUTION>

In [ ]:
# Test using system prompt
text = tokenizer.apply_chat_template([
    {'role': 'system', 'content': SYSTEM_PROMPT},
    {'role': 'user'  , 'content': example_text},
], add_generation_prompt=True, tokenize=False)

# Compare results with system prompt but without LoRA
print(model.fast_generate(
    text, sampling_params=sampling_params,
    lora_request=None,
)[0].outputs[0].text)

# Reasoning model is much better - it's not always correct, since we only trained it for an hour
# It'll be better if we extend the sequence length and train for longer
print(model.fast_generate(
    text, sampling_params=sampling_params,
    lora_request=model.load_lora(f'./{model_name}_grpo'),
)[0].outputs[0].text)

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

 2 - 23 100% SOLUTION </SOLUTION> 3 - 2 = 1 8
<THINK> 2 - 23 100% SOLUTION </SOLUTION> 3 = 1 5
2 - 23 100% SOLUTION </SOLUTION> 3+2 = 5 5
3 - 2 = 1 8

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Okay, let's try to figure out the square root of 101. Hmm, I remember that if I multiply a number by 10 and then take the square root, that gives me the original number. That's probably where I'm supposed to start. Let me try that.

Oh, let me check: 101 times 10 equals 1000, and then I need to take the square root of that. So maybe...70? No, the square root of 1000 should be just 70. That seems right. So the answer should be 70.

Wait, but let me verify. If I square root 1000, does it equal 1000? Because sqrt(1000) is 70, right? So the answer should be 70. And yeah, that seems correct. So I think that's right.

But let me make sure I didn't skip any steps. I triple-checked. If I enter 101 and then select 10 from the numeric keypad, the result should be 70. So that's correct. So the answer is probably 70.

I don't think there's another method. I remember that's the standard approach. If I need to square a number, multiply it by 10. Then, when taking the square root, 10 goes away, and the original number appears. So that makes sense. Yeah, I think that's all there is to it. The sqrt of 101 is 70.
To find the square root of 101, we can use both the direct method and the multiplication method. Here's how we can verify both methods:

1. **Direct Method:**
   If we square root 101, we get 1000, which is exactly the value given in the problem. So the square root must be 70.

2. **Multiplication Method:**
   Given that 101 times 10 is 1000, and then we need to take the square root of that. 1000 divided by 10 is 100, and then squared gives 1000. Thus, the square root of 101 is 70.

3. **Conclusion:**
   Therefore, the square root of 101 is \boxed{70}.</THINK><SOLUTION>70</SOLUTION>

## Performance on Test set

In [ ]:
# test_dataset = load_dataset('openai/gsm8k', 'main', split=['test[:10%]'])
test_dataset = load_dataset('openai/gsm8k', 'main', split='test').map(process_dataset_sample)
test_texts = [
    tokenizer.apply_chat_template([
        {'role': 'system', 'content': SYSTEM_PROMPT},
        {'role': 'user', 'content': sample['prompt'][1]['content']},
    ], add_generation_prompt=True, tokenize=False)
for sample in test_dataset]
print(f'Testing samples:', len(test_dataset))

Map:   0%|          | 0/1319 [00:00<?, ? examples/s]

Testing samples: 1319

In [ ]:
outputs_with_lora = model.fast_generate(
    test_texts, sampling_params=sampling_params,
    lora_request=model.load_lora(f'./{model_name}_grpo'),
)
outputs_without_lora = model.fast_generate(
    test_texts, sampling_params=sampling_params,
    lora_request=None,
)

Adding requests:   0%|          | 0/1319 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1319 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s…

Adding requests:   0%|          | 0/1319 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1319 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s…

In [ ]:
# Compare the correct amount of using and not using LoRA
no_lora_correct_format_cnt = lora_correct_format_cnt = 0
no_lora_correct_answer_cnt = lora_correct_answer_cnt = 0
no_lora_correct_all_cnt = lora_correct_all_cnt = 0
num_test_samples = len(test_dataset)

for output_with_lora, output_without_lora, answer in zip(outputs_with_lora, outputs_without_lora, test_dataset['answer']):
    correct_format = match_format.search(output_with_lora.outputs[0].text)
    correct_answer = (guess := match_number.search(output_with_lora.outputs[0].text)) and guess.group(1) == answer
    correct_all = correct_format and correct_answer
    if correct_format: lora_correct_format_cnt += 1
    if correct_answer: lora_correct_answer_cnt += 1
    if correct_all: lora_correct_all_cnt += 1

    correct_format = match_format.search(output_without_lora.outputs[0].text)
    correct_answer = (guess := match_number.search(output_without_lora.outputs[0].text)) and guess.group(1) == answer
    correct_all = correct_format and correct_answer
    if correct_format: no_lora_correct_format_cnt += 1
    if correct_answer: no_lora_correct_answer_cnt += 1
    if correct_all: no_lora_correct_all_cnt += 1

pd.DataFrame({
    'Without LoRA': {
        'Correct Format': f'{no_lora_correct_format_cnt}/{num_test_samples} ({no_lora_correct_format_cnt / num_test_samples * 100:.2f}%)',
        'Correct Answer': f'{no_lora_correct_answer_cnt}/{num_test_samples} ({no_lora_correct_answer_cnt / num_test_samples * 100:.2f}%)',
        'Correct Both': f'{no_lora_correct_all_cnt}/{num_test_samples} ({no_lora_correct_all_cnt / num_test_samples * 100:.2f}%)',
    },
    'With LoRA': {
        'Correct Format': f'{lora_correct_format_cnt}/{num_test_samples} ({lora_correct_format_cnt / num_test_samples * 100:.2f}%)',
        'Correct Answer': f'{lora_correct_answer_cnt}/{num_test_samples} ({lora_correct_answer_cnt / num_test_samples * 100:.2f}%)',
        'Correct Both': f'{lora_correct_all_cnt}/{num_test_samples} ({lora_correct_all_cnt / num_test_samples * 100:.2f}%)',
    },
    'Improvement': {
        'Correct Format': f'+{lora_correct_format_cnt - no_lora_correct_format_cnt} ({(lora_correct_format_cnt - no_lora_correct_format_cnt) / num_test_samples * 100:.2f}%)',
        'Correct Answer': f'+{lora_correct_answer_cnt - no_lora_correct_answer_cnt} ({(lora_correct_answer_cnt - no_lora_correct_answer_cnt) / num_test_samples * 100:.2f}%)',
        'Correct Both': f'+{lora_correct_all_cnt - no_lora_correct_all_cnt} ({(lora_correct_all_cnt - no_lora_correct_all_cnt) / num_test_samples * 100:.2f}%)',
    }
}).T

                  Correct Format   Correct Answer     Correct Both
Without LoRA     99/1319 (7.51%)  12/1319 (0.91%)   0/1319 (0.00%)
With LoRA     1273/1319 (96.51%)  66/1319 (5.00%)  66/1319 (5.00%)
Improvement       +1174 (89.01%)      +54 (4.09%)      +66 (5.00%)

# Inference

In [ ]:
def generate_with_reasoning(questions, max_completion_length=512):
    conversations = [[                        # Format input using conversation template
        {'role': 'system', 'content': SYSTEM_PROMPT},
        {'role': 'user', 'content': question},
    ] for question in questions]

    prompts = [tokenizer.apply_chat_template( # Apply chat template and tokenize
        conversation,
        add_generation_prompt=True,         # Add assistant prompt
        tokenize=False,                     # Return string, not tokens
    ) for conversation in conversations]

    # Generate response with reasoning-optimized parameters
    inputs = tokenizer(prompts, return_tensors='pt', padding=True).to(model.device)
    start_time = time.time()
    with torch.no_grad():
        output_ids = model.generate(           # Generate response with reasoning-optimized parameters
            **inputs,
            max_new_tokens=max_completion_length,
            temperature=0.7,                # Balance creativity and consistency
            top_p=0.9,                      # Nucleus sampling for quality
            do_sample=True,                 # Enable sampling for varied reasoning paths
            pad_token_id=tokenizer.eos_token_id,
            repetition_penalty=1.1,         # Reduce repetitive reasoning steps
            length_penalty=1.0,             # Neutral preference for response length
            early_stopping=True,            # Stop at natural completion
            streamer=TextStreamer(tokenizer, skip_prompt=True),
        )
    end_time = time.time()
    inference_duration = end_time - start_time
    num_generated_tokens = output_ids.shape[1] - inputs['input_ids'].shape[1]

    output_ids = output_ids[:, inputs['input_ids'][0].shape[-1]:output_ids.shape[-1]]
    responses = tokenizer.batch_decode(output_ids, skip_special_tokens=True) # Decode and extract only the generated portion
    return responses, inference_duration, num_generated_tokens

In [ ]:
test_dataset = load_dataset('openai/gsm8k', 'main', split='test').map(process_dataset_sample)
gsm8k_question = test_dataset[0]['question']
expected_answer = test_dataset[0]['answer']

print('Question:', gsm8k_question, '\nResponse:')
gsm8k_responses, inference_duration, num_generated_tokens = generate_with_reasoning([gsm8k_question], max_completion_length)
gsm8k_response = gsm8k_responses[0]
print('Inference time (secs):', inference_duration)
print('Generated tokens:', num_generated_tokens)

Question: Janet’s ducks lay 16 eggs per day. She eats three for breakfast every morning and bakes muffins for her friends every day with four. She sells the remainder at the farmers' market daily for $2 per fresh duck egg. How much in dollars does she make every day at the farmers' market?
Response:
Okay, let's see here. So Janet has three chickens that lay 16 eggs a day. Every morning when she gets up, she eats one of them for breakfast and makes some muffins with the other two. Then she sells what's left over at the farmer's market for $2 each. The question is asking how much money she makes every day.

Alright, so I need to set up this equation here: total revenue (sales price) minus cost of production equals profit. Let me break it down.

Revenue = 16 eggs * $2 per egg = $32

Cost of production would be the number of eggs eaten by Janet and baked into muffins, which we know as 4*3=12. Therefore, 32 - 12 = 20. So the amount she makes is 20 dollars per day.

Wait, but hold on. There could be other costs involved like food and labor, but those aren't part of this scenario. Just the eggs sold. So even though she may not have made a profit on every sale, the question is asking for the total amount earned over time, so 20 dollars per day seems reasonable. Hmm, okay.

Let me double-check. If she sells 100 eggs per day (which is 1600 eggs per week), that would be $32000 per week. So $200 per day. That seems right. But wait, if she had more than 3 chickens, then the cost of production might go higher. For example, if there were six chickens, then 6*3=18 instead of 12. So maybe that's why the answer is 20. But since she only has three, it should be 16, making $16 per day. Yep, that seems correct.
To determine how much money Janet makes every day at the farmers' market, we can break down the problem into two parts:

1. The number of eggs she lays per day.
2. The price she charges for each egg.

First, we know that Janet lays 16 eggs per day. So the total revenue from selling these eggs is:
\[
16 \times 2 = 32
\]

Next, we need to calculate the cost of producing each egg. Since Janet consumes one of the eggs for breakfast and bakes four for the rest of the day, the cost is:
\[
4 \times 3 = 12
\]

The total cost of production is therefore:
\[
32 - 12 = 20
\]

Thus, Janet earns $20 per day from the sales of her eggs.</THINK><SOLUTION>20</SOLUTION><|end_of_text|>
Inference time (secs): 16.832412719726562
Generated tokens: 539

In [ ]:
# Validate format compliance
has_solution = SOLUTION_START in gsm8k_response and SOLUTION_END in gsm8k_response
print('Reasoning section:', REASONING_END in gsm8k_response)
print('Solution section:', has_solution)

if has_solution: # Check answer accuracy if solution section exists
    try:
        solution_text = gsm8k_response.split(SOLUTION_START)[1].split(SOLUTION_END)[0].strip()
        extracted_number = ''.join(filter(str.isdigit, solution_text))
        expected_number = ''.join(filter(str.isdigit, expected_answer))
        print('Extracted:', solution_text)
        print('Expected:', expected_answer)
        print('Correct:', extracted_number == expected_number)
    except:
        print('Could not extract solution')

Reasoning section: True
Solution section: True
Extracted: 20
Expected: 18
Correct: False